package publish

import (
	"context"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"musiclib/internal/blobstore"
	"musiclib/internal/fsops"
	"musiclib/internal/importer"
	"musiclib/internal/jobs"
	"musiclib/internal/media"
	"musiclib/internal/render"
)

// The executor on real albums: FLAC files generated by the pinned ffmpeg
// in an /import-like directory, imported by the real importer, built by
// the real builder with the real tools, published on ext4.

// flac writes a short FLAC file with Vorbis comments, made by ffmpeg.
func flac(t testing.TB, path string, freq int, tags map[string]string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	args := []string{"-hide_banner", "-nostdin", "-loglevel", "error", "-y", "-f", "lavfi",
		"-i", "sine=frequency=" + strconv.Itoa(freq) + ":duration=0.4:sample_rate=44100", "-ac", "2",
		"-c:a", "flac", "-fflags", "+bitexact", "-flags:a", "+bitexact"}
	for k, v := range tags {
		args = append(args, "-metadata", k+"="+v)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	if out, err := exec.CommandContext(ctx, media.FFmpegPath, append(args, path)...).CombinedOutput(); err != nil {
		t.Fatalf("ffmpeg: %v\n%s", err, out)
	}
}

// album writes an album of n tracks under src/<dir>.
func writeAlbum(t testing.TB, src, dir, artist, title string, n int) {
	t.Helper()
	for i := 1; i <= n; i++ {
		flac(t, filepath.Join(src, dir, strconv.Itoa(i)+".flac"), 300+100*i, map[string]string{
			"ARTIST": artist, "ALBUM": title, "TITLE": "Track " + strconv.Itoa(i), "TRACKNUMBER": strconv.Itoa(i)})
	}
}

// media is a publisher environment with the importer on an import source.
type mediaEnv struct {
	*env
	src string
	im  *importer.Importer
}

func newMediaEnv(t *testing.T) *mediaEnv {
	t.Helper()
	e := newEnv(t)
	m := &mediaEnv{env: e, src: t.TempDir()}
	source, err := fsops.OpenRoot(m.src)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := source.Close(); err != nil {
			t.Error(err)
		}
	})
	tools, err := sharedTools()
	if err != nil {
		t.Fatal(err)
	}
	blobs, err := blobstore.New(e.root("originals"), e.work)
	if err != nil {
		t.Fatal(err)
	}
	if m.im, err = importer.New(importer.Config{Catalog: e.cat, Tools: tools, Blobs: blobs, Source: source, Work: e.work,
		Budget: jobs.NewBudget(), Log: slog.New(slog.NewTextHandler(io.Discard, nil))}); err != nil {
		t.Fatal(err)
	}
	return m
}

// execute is the dispatching executor cmd/musiclibd wires into the pool.
func (m *mediaEnv) execute(ctx context.Context, c *jobs.Claim) error {
	switch c.Kind {
	case jobs.KindScan:
		return m.im.ExecuteScan(ctx, c)
	case jobs.KindImport:
		return m.im.ExecuteImport(ctx, c)
	default:
		return m.p.ExecuteRender(ctx, c)
	}
}

// runPool runs a pool of workers until nothing is pending or running.
func (m *mediaEnv) runPool(workers int) {
	m.t.Helper()
	p, err := jobs.NewPool(m.db, workers, render.Version, m.execute, slog.New(slog.NewTextHandler(io.Discard, nil)))
	if err != nil {
		m.t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() { done <- p.Run(ctx) }()
	deadline := time.Now().Add(3 * time.Minute)
	for m.count(`SELECT count(*) FROM jobs WHERE state IN ('pending', 'running')`) > 0 {
		if time.Now().After(deadline) {
			cancel()
			m.t.Fatal("the pool did not finish within 3 minutes")
		}
		p.Wake()
		time.Sleep(20 * time.Millisecond)
	}
	cancel()
	if err := <-done; err != nil {
		m.t.Fatalf("pool: %v", err)
	}
}

func (m *mediaEnv) importAll() {
	m.t.Helper()
	if _, err := m.cat.CreateImportBatch(context.Background(), uuid.New(), ""); err != nil {
		m.t.Fatal(err)
	}
}

func (m *mediaEnv) albumID(title string) uuid.UUID {
	m.t.Helper()
	var id uuid.UUID
	if err := m.db.QueryRow(context.Background(), `SELECT id FROM albums WHERE title = $1`, title).Scan(&id); err != nil {
		m.t.Fatalf("album %q: %v", title, err)
	}
	return id
}

// publishedResult is the album's published output as a Result.
func (m *mediaEnv) publishedResult(id uuid.UUID) render.Result {
	a := m.album(id)
	return render.Result{AlbumRevision: a.PublishedRevision, RenderVersion: deref(a.PublishedRenderer),
		Removal: a.PublishedPath == nil, Dir: deref(a.PublishedPath), BuildID: deref(a.PublishedBuild),
		ReceiptHash: deref(a.PublishedReceiptHash)}
}

// §13.1 with two workers, and §9.5 "Artista rinominato mentre si
// costruiscono più album": three albums imported, built and published in
// parallel; an artist with two of them renamed; every album converges
// through its own job, the old artist directory is retired, the old claims
// are released.
func TestExecuteRenderTwoWorkersArtistRename(t *testing.T) {
	m := newMediaEnv(t)
	writeAlbum(t, m.src, "a", "Miles Davis", "Kind of Blue", 2)
	writeAlbum(t, m.src, "b", "Miles Davis", "Sketches of Spain", 1)
	writeAlbum(t, m.src, "c", "Bill Evans", "Portrait in Jazz", 1)
	m.importAll()
	m.runPool(2)
	ids := map[string]uuid.UUID{}
	for _, title := range []string{"Kind of Blue", "Sketches of Spain", "Portrait in Jazz"} {
		ids[title] = m.albumID(title)
		m.wantPublished(ids[title], m.publishedResult(ids[title]))
	}
	if got := strings.Join(m.entries("library/Miles Davis"), "|"); got != "Kind of Blue|Sketches of Spain" {
		t.Fatalf("library/Miles Davis holds %q", got)
	}
	m.renameArtist(ids["Kind of Blue"], "Miles Dewey Davis")
	m.runPool(2)
	for _, title := range []string{"Kind of Blue", "Sketches of Spain"} {
		id := ids[title]
		res := m.publishedResult(id)
		if res.Dir != "Miles Dewey Davis/"+title || res.AlbumRevision != m.album(id).Revision {
			t.Fatalf("%s published at %q revision %d", title, res.Dir, res.AlbumRevision)
		}
		m.wantPublished(id, res)
		m.wantClaims(id, res.Dir)
	}
	if got := strings.Join(m.entries("library"), "|"); got != "Bill Evans|Miles Dewey Davis" {
		t.Fatalf("library holds %q", got)
	}
	m.wantWorkClean()
	if n := m.count(`SELECT count(*) FROM jobs WHERE kind = 'render'`); n != 0 {
		t.Fatalf("%d render jobs left", n)
	}
}

// A failure before the journal with a real build: the job fails with the
// preflight's code, the staging is discarded and its space released.
func TestExecuteRenderPreflightFailure(t *testing.T) {
	m := newMediaEnv(t)
	writeAlbum(t, m.src, "a", "Artist", "Album", 1)
	m.write("library/Artist/Album/mine.txt", "the user's")
	m.importAll()
	m.runPool(1)
	id := m.albumID("Album")
	j, ok := m.renderJob(id)
	if !ok || j.State != "failed" || deref(j.ErrorCode) != CodeDestinationOccupied {
		t.Fatalf("job %+v", j)
	}
	if m.album(id).PublishedRevision != 0 {
		t.Fatal("published")
	}
	m.wantWorkClean()
}

// §9.5 "API modifica un album durante la copia" with a real build: the
// build of the old revision is discarded and the new request kept; a
// cancelled build completes nothing (the job stays running for the boot).
func TestExecuteRenderSupersededAndCancelled(t *testing.T) {
	m := newMediaEnv(t)
	writeAlbum(t, m.src, "a", "Artist", "Album", 1)
	m.importAll()
	for {
		c, err := jobs.ClaimNext(context.Background(), m.db, render.Version)
		if err != nil {
			t.Fatal(err)
		}
		if c.Kind == jobs.KindRender {
			m.bump(c.Render.Album.ID) // after the snapshot, before the build
			if err := m.p.ExecuteRender(context.Background(), c); err != nil {
				t.Fatal(err)
			}
			j, _ := m.renderJob(c.Render.Album.ID)
			if j.State != "pending" || m.album(c.Render.Album.ID).PublishedRevision != 0 {
				t.Fatalf("job %s: want pending, nothing published", j.State)
			}
			m.wantWorkClean()
			break
		}
		if err := m.execute(context.Background(), c); err != nil {
			t.Fatal(err)
		}
	}
	c, err := jobs.ClaimNext(context.Background(), m.db, render.Version)
	if err != nil || c == nil {
		t.Fatal(c, err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := m.p.ExecuteRender(ctx, c); err == nil {
		t.Fatal("a cancelled render returned no error")
	}
	if j, _ := m.renderJob(c.Render.Album.ID); j.State != "running" {
		t.Fatalf("job %s after a shutdown, want running", j.State)
	}
}
