// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpAlbumRevision = `-- name: BumpAlbumRevision :one
UPDATE albums SET revision = revision + 1 WHERE id = $1 RETURNING revision
`

// The revision half of §4.3's "bump and enqueue".
func (q *Queries) BumpAlbumRevision(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpAlbumRevision, id)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const clearJobResultAlbums = `-- name: ClearJobResultAlbums :execrows
UPDATE jobs SET result_album_id = NULL WHERE result_album_id = ANY($1::uuid[])
`

// An import's report keeps its folder and outcome; only the link to the
// purged album goes.
func (q *Queries) ClearJobResultAlbums(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearJobResultAlbums, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAlbumTracks = `-- name: CountAlbumTracks :one
SELECT count(*) FROM tracks WHERE album_id = $1
`

func (q *Queries) CountAlbumTracks(ctx context.Context, albumID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbumTracks, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedAlbums = `-- name: CountFailedAlbums :one
SELECT count(*)::bigint AS failed FROM jobs WHERE kind = 'render' AND state = 'failed'
`

// The number of albums the Library's "Da sistemare" filter lists: one
// render job per album (jobs_render_album_key), so the failed render jobs
// count the albums in §10.3 "Errore", active or trashed (NOTES.md N-245).
func (q *Queries) CountFailedAlbums(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedAlbums)
	var failed int64
	err := row.Scan(&failed)
	return failed, err
}

const countTrashedAlbums = `-- name: CountTrashedAlbums :one
SELECT count(*)::bigint AS trashed FROM albums WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountTrashedAlbums(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedAlbums)
	var trashed int64
	err := row.Scan(&trashed)
	return trashed, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM attachments WHERE id = $1 AND album_id = $2
`

type DeleteAttachmentParams struct {
	ID      uuid.UUID
	AlbumID uuid.UUID
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, arg.ID, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteClaim = `-- name: DeleteClaim :execrows
DELETE FROM path_claims WHERE path_key = $1 AND album_id = $2
`

type DeleteClaimParams struct {
	PathKey string
	AlbumID uuid.UUID
}

func (q *Queries) DeleteClaim(ctx context.Context, arg DeleteClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClaim, arg.PathKey, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanArtist = `-- name: DeleteOrphanArtist :execrows
DELETE FROM artists ar
WHERE ar.id = $1 AND NOT EXISTS (SELECT 1 FROM albums al WHERE al.artist_id = ar.id)
`

// An artist left without any album, active or trashed, is deleted in the
// transaction that took its last album away (owner decision, NOTES.md
// N-297). One row or none: an artist that still has an album is kept.
func (q *Queries) DeleteOrphanArtist(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanArtist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePurgedAlbums = `-- name: DeletePurgedAlbums :execrows
DELETE FROM albums WHERE id = ANY($1::uuid[]) AND deleted_at IS NOT NULL
`

func (q *Queries) DeletePurgedAlbums(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurgedAlbums, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePurgedAttachments = `-- name: DeletePurgedAttachments :execrows
DELETE FROM attachments WHERE album_id = ANY($1::uuid[])
`

func (q *Queries) DeletePurgedAttachments(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurgedAttachments, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePurgedClaims = `-- name: DeletePurgedClaims :execrows
DELETE FROM path_claims WHERE album_id = ANY($1::uuid[])
`

func (q *Queries) DeletePurgedClaims(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurgedClaims, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePurgedTracks = `-- name: DeletePurgedTracks :execrows
DELETE FROM tracks WHERE album_id = ANY($1::uuid[])
`

func (q *Queries) DeletePurgedTracks(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurgedTracks, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrack = `-- name: DeleteTrack :execrows
DELETE FROM tracks WHERE id = $1 AND album_id = $2
`

type DeleteTrackParams struct {
	ID      uuid.UUID
	AlbumID uuid.UUID
}

func (q *Queries) DeleteTrack(ctx context.Context, arg DeleteTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrack, arg.ID, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const doctorAlbums = `-- name: DoctorAlbums :many
SELECT al.id, ar.name AS artist_name, al.title,
       (al.deleted_at IS NULL)::boolean AS active,
       al.revision, al.published_path, al.published_revision,
       al.published_renderer, al.published_build, al.published_receipt_hash,
       j.state AS job_state
FROM albums al JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN jobs j ON j.kind = 'render' AND j.album_id = al.id
ORDER BY al.id
`

type DoctorAlbumsRow struct {
	ID                   uuid.UUID
	ArtistName           string
	Title                string
	Active               bool
	Revision             int64
	PublishedPath        *string
	PublishedRevision    int64
	PublishedRenderer    *string
	PublishedBuild       *uuid.UUID
	PublishedReceiptHash *string
	JobState             *string
}

func (q *Queries) DoctorAlbums(ctx context.Context) ([]DoctorAlbumsRow, error) {
	rows, err := q.db.Query(ctx, doctorAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DoctorAlbumsRow
	for rows.Next() {
		var i DoctorAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistName,
			&i.Title,
			&i.Active,
			&i.Revision,
			&i.PublishedPath,
			&i.PublishedRevision,
			&i.PublishedRenderer,
			&i.PublishedBuild,
			&i.PublishedReceiptHash,
			&i.JobState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doctorBlobs = `-- name: DoctorBlobs :many
SELECT b.hash, b.size, EXISTS (
    SELECT 1 FROM tracks t WHERE t.blob_hash = b.hash OR t.lyrics_hash = b.hash
) OR EXISTS (SELECT 1 FROM attachments a WHERE a.blob_hash = b.hash)
  OR EXISTS (SELECT 1 FROM albums al WHERE al.cover_hash = b.hash) AS referenced
FROM blobs b ORDER BY b.hash
`

type DoctorBlobsRow struct {
	Hash       string
	Size       int64
	Referenced *bool
}

// Offline integrity inventory (§11.3). References include trashed albums: their
// originals still belong to the catalog. The list includes unreferenced rows
// so doctor can distinguish them from missing files and orphaned files.
func (q *Queries) DoctorBlobs(ctx context.Context) ([]DoctorBlobsRow, error) {
	rows, err := q.db.Query(ctx, doctorBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DoctorBlobsRow
	for rows.Next() {
		var i DoctorBlobsRow
		if err := rows.Scan(&i.Hash, &i.Size, &i.Referenced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doctorClaims = `-- name: DoctorClaims :many
SELECT path_key, path, album_id FROM path_claims ORDER BY path_key
`

func (q *Queries) DoctorClaims(ctx context.Context) ([]PathClaim, error) {
	rows, err := q.db.Query(ctx, doctorClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PathClaim
	for rows.Next() {
		var i PathClaim
		if err := rows.Scan(&i.PathKey, &i.Path, &i.AlbumID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doctorPublication = `-- name: DoctorPublication :many
SELECT album_id, build_id, old_path, new_path FROM publication
`

type DoctorPublicationRow struct {
	AlbumID uuid.UUID
	BuildID uuid.UUID
	OldPath *string
	NewPath *string
}

func (q *Queries) DoctorPublication(ctx context.Context) ([]DoctorPublicationRow, error) {
	rows, err := q.db.Query(ctx, doctorPublication)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DoctorPublicationRow
	for rows.Next() {
		var i DoctorPublicationRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.BuildID,
			&i.OldPath,
			&i.NewPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doctorStructuralIssues = `-- name: DoctorStructuralIssues :many
SELECT 'doctor_album_no_tracks'::text AS code, id::text AS entity
FROM albums a WHERE deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM tracks t WHERE t.album_id=a.id)
UNION ALL
SELECT 'doctor_missing_blob', t.id::text FROM tracks t LEFT JOIN blobs b ON b.hash=t.blob_hash WHERE b.hash IS NULL
UNION ALL
SELECT 'doctor_missing_blob', a.id::text FROM attachments a LEFT JOIN blobs b ON b.hash=a.blob_hash WHERE b.hash IS NULL
UNION ALL
SELECT 'doctor_missing_album', j.id::text FROM jobs j LEFT JOIN albums a ON a.id=j.album_id WHERE j.kind='render' AND a.id IS NULL
ORDER BY code, entity
`

type DoctorStructuralIssuesRow struct {
	Code   string
	Entity string
}

func (q *Queries) DoctorStructuralIssues(ctx context.Context) ([]DoctorStructuralIssuesRow, error) {
	rows, err := q.db.Query(ctx, doctorStructuralIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DoctorStructuralIssuesRow
	for rows.Next() {
		var i DoctorStructuralIssuesRow
		if err := rows.Scan(&i.Code, &i.Entity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveAlbumByFolder = `-- name: FindActiveAlbumByFolder :one
SELECT id, title FROM albums
WHERE artist_id = $1 AND folder_key = $2 AND deleted_at IS NULL AND id <> $3
`

type FindActiveAlbumByFolderParams struct {
	ArtistID  uuid.UUID
	FolderKey string
	Exclude   uuid.UUID
}

type FindActiveAlbumByFolderRow struct {
	ID    uuid.UUID
	Title string
}

// The active album holding a folder under an artist, other than exclude
// (albums_active_folder_key, §4.2).
func (q *Queries) FindActiveAlbumByFolder(ctx context.Context, arg FindActiveAlbumByFolderParams) (FindActiveAlbumByFolderRow, error) {
	row := q.db.QueryRow(ctx, findActiveAlbumByFolder, arg.ArtistID, arg.FolderKey, arg.Exclude)
	var i FindActiveAlbumByFolderRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, artist_id, title, folder_key, year, genre, compilation, cover_hash, revision, deleted_at, import_fingerprint, published_path, published_revision, published_renderer, published_build, published_receipt_hash FROM albums WHERE id = $1
`

// Albums (§4.2, §4.3).
func (q *Queries) GetAlbum(ctx context.Context, id uuid.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.FolderKey,
		&i.Year,
		&i.Genre,
		&i.Compilation,
		&i.CoverHash,
		&i.Revision,
		&i.DeletedAt,
		&i.ImportFingerprint,
		&i.PublishedPath,
		&i.PublishedRevision,
		&i.PublishedRenderer,
		&i.PublishedBuild,
		&i.PublishedReceiptHash,
	)
	return i, err
}

const getAlbumAttachment = `-- name: GetAlbumAttachment :one
SELECT a.id, a.rel_path, a.path_key, a.blob_hash FROM attachments a
WHERE a.id = $1 AND a.album_id = $2
`

type GetAlbumAttachmentParams struct {
	ID      uuid.UUID
	AlbumID uuid.UUID
}

type GetAlbumAttachmentRow struct {
	ID       uuid.UUID
	RelPath  string
	PathKey  string
	BlobHash string
}

// An attachment of an album: the album is part of the key, so an
// attachment of another album is not found (§10.2 downloads by id).
func (q *Queries) GetAlbumAttachment(ctx context.Context, arg GetAlbumAttachmentParams) (GetAlbumAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAlbumAttachment, arg.ID, arg.AlbumID)
	var i GetAlbumAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.RelPath,
		&i.PathKey,
		&i.BlobHash,
	)
	return i, err
}

const getAlbumByFingerprint = `-- name: GetAlbumByFingerprint :one
SELECT id, deleted_at FROM albums WHERE import_fingerprint = $1
`

type GetAlbumByFingerprintRow struct {
	ID        uuid.UUID
	DeletedAt *time.Time
}

func (q *Queries) GetAlbumByFingerprint(ctx context.Context, importFingerprint *string) (GetAlbumByFingerprintRow, error) {
	row := q.db.QueryRow(ctx, getAlbumByFingerprint, importFingerprint)
	var i GetAlbumByFingerprintRow
	err := row.Scan(&i.ID, &i.DeletedAt)
	return i, err
}

const getAlbumPathState = `-- name: GetAlbumPathState :one
SELECT (al.deleted_at IS NULL)::boolean AS active, al.title, ar.name AS artist_name, al.published_path
FROM albums al JOIN artists ar ON ar.id = al.artist_id
WHERE al.id = $1
`

type GetAlbumPathStateRow struct {
	Active        bool
	Title         string
	ArtistName    string
	PublishedPath *string
}

// What the path claims of an album are derived from (§5.3).
func (q *Queries) GetAlbumPathState(ctx context.Context, id uuid.UUID) (GetAlbumPathStateRow, error) {
	row := q.db.QueryRow(ctx, getAlbumPathState, id)
	var i GetAlbumPathStateRow
	err := row.Scan(
		&i.Active,
		&i.Title,
		&i.ArtistName,
		&i.PublishedPath,
	)
	return i, err
}

const getAlbumStatus = `-- name: GetAlbumStatus :one
SELECT al.id, al.revision, (al.deleted_at IS NOT NULL)::boolean AS trashed,
       al.published_path, al.published_revision, al.published_renderer,
       j.id AS job_id, j.state AS job_state, j.error_code AS job_error_code,
       j.error_message AS job_error_message, j.queued_at AS job_queued_at, j.updated_at AS job_updated_at
FROM albums al
LEFT JOIN jobs j ON j.kind = 'render' AND j.album_id = al.id
WHERE al.id = $1
`

type GetAlbumStatusRow struct {
	ID                uuid.UUID
	Revision          int64
	Trashed           bool
	PublishedPath     *string
	PublishedRevision int64
	PublishedRenderer *string
	JobID             *uuid.UUID
	JobState          *string
	JobErrorCode      *string
	JobErrorMessage   *string
	JobQueuedAt       *time.Time
	JobUpdatedAt      *time.Time
}

// The processing state (§10.2 GET /api/albums/{id}/status): revisions,
// published renderer and path (relative to library/), the render job.
func (q *Queries) GetAlbumStatus(ctx context.Context, id uuid.UUID) (GetAlbumStatusRow, error) {
	row := q.db.QueryRow(ctx, getAlbumStatus, id)
	var i GetAlbumStatusRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Trashed,
		&i.PublishedPath,
		&i.PublishedRevision,
		&i.PublishedRenderer,
		&i.JobID,
		&i.JobState,
		&i.JobErrorCode,
		&i.JobErrorMessage,
		&i.JobQueuedAt,
		&i.JobUpdatedAt,
	)
	return i, err
}

const getAlbumTrack = `-- name: GetAlbumTrack :one
SELECT id, lyrics_hash FROM tracks WHERE id = $1 AND album_id = $2
`

type GetAlbumTrackParams struct {
	ID      uuid.UUID
	AlbumID uuid.UUID
}

type GetAlbumTrackRow struct {
	ID         uuid.UUID
	LyricsHash *string
}

// A track of an album, with the same rule as GetAlbumAttachment.
func (q *Queries) GetAlbumTrack(ctx context.Context, arg GetAlbumTrackParams) (GetAlbumTrackRow, error) {
	row := q.db.QueryRow(ctx, getAlbumTrack, arg.ID, arg.AlbumID)
	var i GetAlbumTrackRow
	err := row.Scan(&i.ID, &i.LyricsHash)
	return i, err
}

const getAlbumView = `-- name: GetAlbumView :one
SELECT al.id, al.artist_id, ar.name AS artist_name, al.title, al.year, al.genre, al.compilation,
       (al.deleted_at IS NOT NULL)::boolean AS trashed, al.revision,
       al.cover_hash, cb.size AS cover_size, cb.format AS cover_format
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN blobs cb ON cb.hash = al.cover_hash
WHERE al.id = $1
`

type GetAlbumViewRow struct {
	ID          uuid.UUID
	ArtistID    uuid.UUID
	ArtistName  string
	Title       string
	Year        *int32
	Genre       *string
	Compilation bool
	Trashed     bool
	Revision    int64
	CoverHash   *string
	CoverSize   *int64
	CoverFormat *string
}

// The desired album (§10.2 GET /api/albums/{id}): no published column.
func (q *Queries) GetAlbumView(ctx context.Context, id uuid.UUID) (GetAlbumViewRow, error) {
	row := q.db.QueryRow(ctx, getAlbumView, id)
	var i GetAlbumViewRow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.Title,
		&i.Year,
		&i.Genre,
		&i.Compilation,
		&i.Trashed,
		&i.Revision,
		&i.CoverHash,
		&i.CoverSize,
		&i.CoverFormat,
	)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, folder_key, revision FROM artists WHERE id = $1
`

// Artists (§4.3, §7.6).
func (q *Queries) GetArtist(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderKey,
		&i.Revision,
	)
	return i, err
}

const getArtistByFolderKey = `-- name: GetArtistByFolderKey :one
SELECT id, name, folder_key, revision FROM artists WHERE folder_key = $1
`

func (q *Queries) GetArtistByFolderKey(ctx context.Context, folderKey string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByFolderKey, folderKey)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderKey,
		&i.Revision,
	)
	return i, err
}

const getBlobs = `-- name: GetBlobs :many
SELECT hash, size, format FROM blobs WHERE hash = ANY($1::text[]) ORDER BY hash
`

type GetBlobsRow struct {
	Hash   string
	Size   int64
	Format *string
}

func (q *Queries) GetBlobs(ctx context.Context, hashes []string) ([]GetBlobsRow, error) {
	rows, err := q.db.Query(ctx, getBlobs, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlobsRow
	for rows.Next() {
		var i GetBlobsRow
		if err := rows.Scan(&i.Hash, &i.Size, &i.Format); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaims = `-- name: GetClaims :many
SELECT path_key, path, album_id FROM path_claims WHERE path_key = ANY($1::text[]) ORDER BY path_key
`

func (q *Queries) GetClaims(ctx context.Context, keys []string) ([]PathClaim, error) {
	rows, err := q.db.Query(ctx, getClaims, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PathClaim
	for rows.Next() {
		var i PathClaim
		if err := rows.Scan(&i.PathKey, &i.Path, &i.AlbumID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublication = `-- name: GetPublication :one
SELECT album_id, old_path, new_path FROM publication WHERE id = 1
`

type GetPublicationRow struct {
	AlbumID uuid.UUID
	OldPath *string
	NewPath *string
}

// The publication journal, zero or one row (§9.3).
func (q *Queries) GetPublication(ctx context.Context) (GetPublicationRow, error) {
	row := q.db.QueryRow(ctx, getPublication)
	var i GetPublicationRow
	err := row.Scan(&i.AlbumID, &i.OldPath, &i.NewPath)
	return i, err
}

const insertAlbum = `-- name: InsertAlbum :exec
INSERT INTO albums (id, artist_id, title, folder_key, year, genre, compilation, cover_hash, revision, import_fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 1, $9)
`

type InsertAlbumParams struct {
	ID                uuid.UUID
	ArtistID          uuid.UUID
	Title             string
	FolderKey         string
	Year              *int32
	Genre             *string
	Compilation       bool
	CoverHash         *string
	ImportFingerprint *string
}

func (q *Queries) InsertAlbum(ctx context.Context, arg InsertAlbumParams) error {
	_, err := q.db.Exec(ctx, insertAlbum,
		arg.ID,
		arg.ArtistID,
		arg.Title,
		arg.FolderKey,
		arg.Year,
		arg.Genre,
		arg.Compilation,
		arg.CoverHash,
		arg.ImportFingerprint,
	)
	return err
}

const insertArtist = `-- name: InsertArtist :exec
INSERT INTO artists (id, name, folder_key, revision) VALUES ($1, $2, $3, 1)
`

type InsertArtistParams struct {
	ID        uuid.UUID
	Name      string
	FolderKey string
}

func (q *Queries) InsertArtist(ctx context.Context, arg InsertArtistParams) error {
	_, err := q.db.Exec(ctx, insertArtist, arg.ID, arg.Name, arg.FolderKey)
	return err
}

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO attachments (id, album_id, rel_path, path_key, blob_hash) VALUES ($1, $2, $3, $4, $5)
`

type InsertAttachmentParams struct {
	ID       uuid.UUID
	AlbumID  uuid.UUID
	RelPath  string
	PathKey  string
	BlobHash string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertAttachment,
		arg.ID,
		arg.AlbumID,
		arg.RelPath,
		arg.PathKey,
		arg.BlobHash,
	)
	return err
}

type InsertAttachmentsParams struct {
	ID       uuid.UUID
	AlbumID  uuid.UUID
	RelPath  string
	PathKey  string
	BlobHash string
}

const insertBlobs = `-- name: InsertBlobs :exec
INSERT INTO blobs (hash, size, format, duration_ms, created_at)
SELECT u.hash, u.size, NULLIF(u.format, ''), NULLIF(u.duration_ms, -1), now()
FROM (SELECT unnest($1::text[]) AS hash, unnest($2::bigint[]) AS size,
             unnest($3::text[]) AS format, unnest($4::bigint[]) AS duration_ms) AS u
ON CONFLICT (hash) DO NOTHING
`

type InsertBlobsParams struct {
	Hashes    []string
	Sizes     []int64
	Formats   []string
	Durations []int64
}

// Blobs (§7.5, §7.6): the rows of blobs already pinned on disk. An existing
// row is kept; the caller compares size and format with GetBlobs. A
// duration of -1 is unknown (NULL, NOTES.md N-300).
func (q *Queries) InsertBlobs(ctx context.Context, arg InsertBlobsParams) error {
	_, err := q.db.Exec(ctx, insertBlobs,
		arg.Hashes,
		arg.Sizes,
		arg.Formats,
		arg.Durations,
	)
	return err
}

type InsertTracksParams struct {
	ID         uuid.UUID
	AlbumID    uuid.UUID
	Disc       int32
	No         int32
	Title      string
	Artist     *string
	Genre      *string
	BlobHash   string
	SourcePath string
	LyricsHash *string
}

const listAlbumAttachmentPaths = `-- name: ListAlbumAttachmentPaths :many
SELECT id, rel_path FROM attachments WHERE album_id = $1 ORDER BY path_key COLLATE "C", id
`

type ListAlbumAttachmentPathsRow struct {
	ID      uuid.UUID
	RelPath string
}

func (q *Queries) ListAlbumAttachmentPaths(ctx context.Context, albumID uuid.UUID) ([]ListAlbumAttachmentPathsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumAttachmentPaths, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumAttachmentPathsRow
	for rows.Next() {
		var i ListAlbumAttachmentPathsRow
		if err := rows.Scan(&i.ID, &i.RelPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumAttachmentViews = `-- name: ListAlbumAttachmentViews :many
SELECT a.id, a.rel_path, a.blob_hash, b.size AS blob_size, b.format AS blob_format
FROM attachments a
JOIN blobs b ON b.hash = a.blob_hash
WHERE a.album_id = $1
ORDER BY a.path_key COLLATE "C", a.id
`

type ListAlbumAttachmentViewsRow struct {
	ID         uuid.UUID
	RelPath    string
	BlobHash   string
	BlobSize   int64
	BlobFormat *string
}

func (q *Queries) ListAlbumAttachmentViews(ctx context.Context, albumID uuid.UUID) ([]ListAlbumAttachmentViewsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumAttachmentViews, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumAttachmentViewsRow
	for rows.Next() {
		var i ListAlbumAttachmentViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumAudioFormats = `-- name: ListAlbumAudioFormats :many
SELECT DISTINCT b.format FROM tracks t JOIN blobs b ON b.hash = t.blob_hash
WHERE t.album_id = $1 AND b.format IS NOT NULL ORDER BY b.format
`

// The audio formats of an album's tracks, for the per-format rules of a
// change (N-162).
func (q *Queries) ListAlbumAudioFormats(ctx context.Context, albumID uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listAlbumAudioFormats, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var format *string
		if err := rows.Scan(&format); err != nil {
			return nil, err
		}
		items = append(items, format)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumCards = `-- name: ListAlbumCards :many
SELECT al.id, al.title, ar.name AS artist_name,
       (al.cover_hash IS NOT NULL)::boolean AS has_cover, (al.deleted_at IS NOT NULL)::boolean AS trashed
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
WHERE al.id = ANY($1::uuid[])
`

type ListAlbumCardsRow struct {
	ID         uuid.UUID
	Title      string
	ArtistName string
	HasCover   bool
	Trashed    bool
}

// Albums as the queue views show them (NOTES.md N-286): the title, the
// artist, whether there is a cover and whether the album is in the trash.
func (q *Queries) ListAlbumCards(ctx context.Context, ids []uuid.UUID) ([]ListAlbumCardsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumCards, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumCardsRow
	for rows.Next() {
		var i ListAlbumCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.HasCover,
			&i.Trashed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumClaims = `-- name: ListAlbumClaims :many
SELECT path_key, path FROM path_claims WHERE album_id = $1 ORDER BY path_key
`

type ListAlbumClaimsRow struct {
	PathKey string
	Path    string
}

// Path claims (§5.3).
func (q *Queries) ListAlbumClaims(ctx context.Context, albumID uuid.UUID) ([]ListAlbumClaimsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumClaims, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumClaimsRow
	for rows.Next() {
		var i ListAlbumClaimsRow
		if err := rows.Scan(&i.PathKey, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumSummaries = `-- name: ListAlbumSummaries :many
SELECT al.id, al.revision, al.artist_id, ar.name AS artist_name, ar.folder_key AS artist_key,
       al.title, al.folder_key AS title_key, al.year, al.genre, al.compilation,
       (al.deleted_at IS NOT NULL)::boolean AS trashed,
       al.cover_hash, cb.size AS cover_size, cb.format AS cover_format,
       al.published_path, al.published_revision, al.published_renderer,
       j.state AS job_state, j.error_code AS job_error_code, j.error_message AS job_error_message
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN blobs cb ON cb.hash = al.cover_hash
LEFT JOIN jobs j ON j.kind = 'render' AND j.album_id = al.id
WHERE (CASE WHEN $1::boolean THEN j.state IS NOT DISTINCT FROM 'failed'
            ELSE (al.deleted_at IS NOT NULL) = $2::boolean END)
  AND (NOT $3::boolean OR al.artist_id = $4::uuid)
  AND ($5::boolean
       OR (ar.folder_key COLLATE "C", al.folder_key COLLATE "C", al.id)
          > ($6::text, $7::text, $8::uuid))
ORDER BY ar.folder_key COLLATE "C", al.folder_key COLLATE "C", al.id
LIMIT $9::int
`

type ListAlbumSummariesParams struct {
	Failed      bool
	Trashed     bool
	ByArtist    bool
	ArtistID    uuid.UUID
	First       bool
	AfterArtist string
	AfterTitle  string
	AfterID     uuid.UUID
	Lim         int32
}

type ListAlbumSummariesRow struct {
	ID                uuid.UUID
	Revision          int64
	ArtistID          uuid.UUID
	ArtistName        string
	ArtistKey         string
	Title             string
	TitleKey          string
	Year              *int32
	Genre             *string
	Compilation       bool
	Trashed           bool
	CoverHash         *string
	CoverSize         *int64
	CoverFormat       *string
	PublishedPath     *string
	PublishedRevision int64
	PublishedRenderer *string
	JobState          *string
	JobErrorCode      *string
	JobErrorMessage   *string
}

// §10.2 GET /api/albums: album summaries in the library's order, the
// artist's folder key, then the album's, then the id, byte-wise (COLLATE
// "C"). Keyset pagination: the page starts after the cursor's triple
// (NOTES.md N-190). The text search is applied by the caller with the
// normalization of internal/names, never with SQL lower() (§5.2). With
// @failed the page keeps only the albums whose render job failed (§10.3
// "Errore"), active or trashed, and @trashed is ignored (NOTES.md N-245).
func (q *Queries) ListAlbumSummaries(ctx context.Context, arg ListAlbumSummariesParams) ([]ListAlbumSummariesRow, error) {
	rows, err := q.db.Query(ctx, listAlbumSummaries,
		arg.Failed,
		arg.Trashed,
		arg.ByArtist,
		arg.ArtistID,
		arg.First,
		arg.AfterArtist,
		arg.AfterTitle,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumSummariesRow
	for rows.Next() {
		var i ListAlbumSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistKey,
			&i.Title,
			&i.TitleKey,
			&i.Year,
			&i.Genre,
			&i.Compilation,
			&i.Trashed,
			&i.CoverHash,
			&i.CoverSize,
			&i.CoverFormat,
			&i.PublishedPath,
			&i.PublishedRevision,
			&i.PublishedRenderer,
			&i.JobState,
			&i.JobErrorCode,
			&i.JobErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTrackViews = `-- name: ListAlbumTrackViews :many
SELECT t.id, t.disc, t.no, t.title, t.artist, t.genre, t.source_path,
       t.blob_hash, b.size AS blob_size, b.format AS blob_format, b.duration_ms AS blob_duration_ms, t.lyrics_hash
FROM tracks t
JOIN blobs b ON b.hash = t.blob_hash
WHERE t.album_id = $1
ORDER BY t.disc, t.no, t.id
`

type ListAlbumTrackViewsRow struct {
	ID             uuid.UUID
	Disc           int32
	No             int32
	Title          string
	Artist         *string
	Genre          *string
	SourcePath     string
	BlobHash       string
	BlobSize       int64
	BlobFormat     *string
	BlobDurationMs *int64
	LyricsHash     *string
}

func (q *Queries) ListAlbumTrackViews(ctx context.Context, albumID uuid.UUID) ([]ListAlbumTrackViewsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTrackViews, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTrackViewsRow
	for rows.Next() {
		var i ListAlbumTrackViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.SourcePath,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
			&i.BlobDurationMs,
			&i.LyricsHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTracks = `-- name: ListAlbumTracks :many
SELECT id, disc, no, title, artist, genre, blob_hash FROM tracks WHERE album_id = $1 ORDER BY disc, no, id
`

type ListAlbumTracksRow struct {
	ID       uuid.UUID
	Disc     int32
	No       int32
	Title    string
	Artist   *string
	Genre    *string
	BlobHash string
}

func (q *Queries) ListAlbumTracks(ctx context.Context, albumID uuid.UUID) ([]ListAlbumTracksRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTracks, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTracksRow
	for rows.Next() {
		var i ListAlbumTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.BlobHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistAlbumIDs = `-- name: ListArtistAlbumIDs :many
SELECT id FROM albums WHERE artist_id = $1 ORDER BY id
`

// Every album of an artist, trashed ones included: a rename changes the
// tags and the folder of all of them (§4.3).
func (q *Queries) ListArtistAlbumIDs(ctx context.Context, artistID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listArtistAlbumIDs, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many

SELECT id, name, folder_key, revision FROM artists
ORDER BY folder_key COLLATE "C", id
`

// The API's reads (§10.1, §10.2). They run in one REPEATABLE READ snapshot
// (store.InSnapshotTx), so that a representation and its revision agree.
// Orders are deterministic and byte-wise (COLLATE "C"), independent of the
// database's locale.
// Every artist of the catalog, those without albums included (owner
// decision N-146: the list feeds the album editor's artist selector).
func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderKey,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeableAlbums = `-- name: ListPurgeableAlbums :many
SELECT al.id, al.artist_id FROM albums al
WHERE al.deleted_at IS NOT NULL AND al.published_path IS NULL
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'render' AND j.album_id = al.id)
  AND NOT EXISTS (SELECT 1 FROM publication p WHERE p.album_id = al.id)
ORDER BY al.id
`

type ListPurgeableAlbumsRow struct {
	ID       uuid.UUID
	ArtistID uuid.UUID
}

// Emptying the trash (POST /api/trash/empty): the catalog rows of the
// trashed albums whose removal from library/ is complete are deleted,
// never a blob. An album is purgeable when it is in the trash, has no
// published output, no render job (pending, running or failed) and no
// publication journal. Every row that could change that is written under
// the catalog lock (enqueue, PREPARE, FINALIZE), which the caller holds.
func (q *Queries) ListPurgeableAlbums(ctx context.Context) ([]ListPurgeableAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listPurgeableAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurgeableAlbumsRow
	for rows.Next() {
		var i ListPurgeableAlbumsRow
		if err := rows.Scan(&i.ID, &i.ArtistID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCatalog = `-- name: LockCatalog :exec

SELECT pg_advisory_xact_lock(7884786317834415207)
`

// Catalog queries (DESIGN.md §4, §5.3, §7.6). Every statement here that
// writes runs inside store.InCatalogTx, under the catalog lock below.
// The catalog lock of §5.3: one transaction-scoped advisory lock with a
// constant key, taken first by every catalog mutation. The key is the ASCII
// "mlcatalg", distinct from the migration lock "mlmigrat" (N-053).
func (q *Queries) LockCatalog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCatalog)
	return err
}

const renameArtist = `-- name: RenameArtist :one
UPDATE artists SET name = $2, folder_key = $3, revision = revision + 1
WHERE id = $1
RETURNING revision
`

type RenameArtistParams struct {
	ID        uuid.UUID
	Name      string
	FolderKey string
}

func (q *Queries) RenameArtist(ctx context.Context, arg RenameArtistParams) (int64, error) {
	row := q.db.QueryRow(ctx, renameArtist, arg.ID, arg.Name, arg.FolderKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const setAlbumCover = `-- name: SetAlbumCover :exec

UPDATE albums SET cover_hash = $1 WHERE id = $2
`

type SetAlbumCoverParams struct {
	CoverHash *string
	ID        uuid.UUID
}

// The editor's content operations (§4.3, §10.2): cover, attachments,
// lyrics and track deletion. Each runs in store.InCatalogTx with the
// album's revision compared first.
func (q *Queries) SetAlbumCover(ctx context.Context, arg SetAlbumCoverParams) error {
	_, err := q.db.Exec(ctx, setAlbumCover, arg.CoverHash, arg.ID)
	return err
}

const setAlbumTrashed = `-- name: SetAlbumTrashed :exec
UPDATE albums SET deleted_at = CASE WHEN $1::boolean THEN now() END WHERE id = $2
`

type SetAlbumTrashedParams struct {
	Trashed bool
	ID      uuid.UUID
}

// Trash (deleted_at = now) or restore (deleted_at = NULL), §4.3.
func (q *Queries) SetAlbumTrashed(ctx context.Context, arg SetAlbumTrashedParams) error {
	_, err := q.db.Exec(ctx, setAlbumTrashed, arg.Trashed, arg.ID)
	return err
}

const setBlobDuration = `-- name: SetBlobDuration :execrows
UPDATE blobs SET duration_ms = $1
WHERE hash = $2 AND duration_ms IS NULL AND format IN ('flac', 'mp3', 'm4a-aac', 'm4a-alac')
`

type SetBlobDurationParams struct {
	DurationMs *int64
	Hash       string
}

// A probed duration replaces "unknown", never a known one (N-300, N-301):
// the first value recorded stays, whatever a later probe says. Only an audio
// blob has one (blobs_duration_check); any other row is left alone.
func (q *Queries) SetBlobDuration(ctx context.Context, arg SetBlobDurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBlobDuration, arg.DurationMs, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBlobFormat = `-- name: SetBlobFormat :execrows
UPDATE blobs SET format = $1 WHERE hash = $2 AND format IS NULL
`

type SetBlobFormatParams struct {
	Format *string
	Hash   string
}

// A content-derived format replaces "unknown", never another format.
func (q *Queries) SetBlobFormat(ctx context.Context, arg SetBlobFormatParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBlobFormat, arg.Format, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTrackLyrics = `-- name: SetTrackLyrics :execrows
UPDATE tracks SET lyrics_hash = $1 WHERE id = $2 AND album_id = $3
`

type SetTrackLyricsParams struct {
	LyricsHash *string
	ID         uuid.UUID
	AlbumID    uuid.UUID
}

func (q *Queries) SetTrackLyrics(ctx context.Context, arg SetTrackLyricsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTrackLyrics, arg.LyricsHash, arg.ID, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAlbumMetadata = `-- name: UpdateAlbumMetadata :exec
UPDATE albums
SET artist_id = $1, title = $2, folder_key = $3, year = $4,
    genre = $5, compilation = $6
WHERE id = $7
`

type UpdateAlbumMetadataParams struct {
	ArtistID    uuid.UUID
	Title       string
	FolderKey   string
	Year        *int32
	Genre       *string
	Compilation bool
	ID          uuid.UUID
}

func (q *Queries) UpdateAlbumMetadata(ctx context.Context, arg UpdateAlbumMetadataParams) error {
	_, err := q.db.Exec(ctx, updateAlbumMetadata,
		arg.ArtistID,
		arg.Title,
		arg.FolderKey,
		arg.Year,
		arg.Genre,
		arg.Compilation,
		arg.ID,
	)
	return err
}

const updateTrack = `-- name: UpdateTrack :execrows
UPDATE tracks SET disc = $1, no = $2, title = $3, artist = $4, genre = $5
WHERE id = $6 AND album_id = $7
`

type UpdateTrackParams struct {
	Disc    int32
	No      int32
	Title   string
	Artist  *string
	Genre   *string
	ID      uuid.UUID
	AlbumID uuid.UUID
}

// The (album_id, disc, no) constraint is deferred to the commit, so a swap
// of numbers needs no temporary values (§4.2, §12.2).
func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTrack,
		arg.Disc,
		arg.No,
		arg.Title,
		arg.Artist,
		arg.Genre,
		arg.ID,
		arg.AlbumID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertClaim = `-- name: UpsertClaim :execrows
INSERT INTO path_claims (path_key, path, album_id) VALUES ($1, $2, $3)
ON CONFLICT (path_key) DO UPDATE SET path = EXCLUDED.path
WHERE path_claims.album_id = EXCLUDED.album_id
`

type UpsertClaimParams struct {
	PathKey string
	Path    string
	AlbumID uuid.UUID
}

// Inserts a claim, or updates the display path of a claim the album already
// owns. Zero rows means another album owns the key.
func (q *Queries) UpsertClaim(ctx context.Context, arg UpsertClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertClaim, arg.PathKey, arg.Path, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
