// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpAlbumRevision = `-- name: BumpAlbumRevision :one
UPDATE albums SET revision = revision + 1 WHERE id = $1 RETURNING revision
`

// The revision half of §4.3's "bump and enqueue".
func (q *Queries) BumpAlbumRevision(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpAlbumRevision, id)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const deleteClaim = `-- name: DeleteClaim :execrows
DELETE FROM path_claims WHERE path_key = $1 AND album_id = $2
`

type DeleteClaimParams struct {
	PathKey string
	AlbumID uuid.UUID
}

func (q *Queries) DeleteClaim(ctx context.Context, arg DeleteClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClaim, arg.PathKey, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveAlbumByFolder = `-- name: FindActiveAlbumByFolder :one
SELECT id, title FROM albums
WHERE artist_id = $1 AND folder_key = $2 AND deleted_at IS NULL AND id <> $3
`

type FindActiveAlbumByFolderParams struct {
	ArtistID  uuid.UUID
	FolderKey string
	Exclude   uuid.UUID
}

type FindActiveAlbumByFolderRow struct {
	ID    uuid.UUID
	Title string
}

// The active album holding a folder under an artist, other than exclude
// (albums_active_folder_key, §4.2).
func (q *Queries) FindActiveAlbumByFolder(ctx context.Context, arg FindActiveAlbumByFolderParams) (FindActiveAlbumByFolderRow, error) {
	row := q.db.QueryRow(ctx, findActiveAlbumByFolder, arg.ArtistID, arg.FolderKey, arg.Exclude)
	var i FindActiveAlbumByFolderRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, artist_id, title, folder_key, year, genre, compilation, cover_hash, revision, deleted_at, import_fingerprint, published_path, published_revision, published_renderer, published_build, published_receipt_hash FROM albums WHERE id = $1
`

// Albums (§4.2, §4.3).
func (q *Queries) GetAlbum(ctx context.Context, id uuid.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.FolderKey,
		&i.Year,
		&i.Genre,
		&i.Compilation,
		&i.CoverHash,
		&i.Revision,
		&i.DeletedAt,
		&i.ImportFingerprint,
		&i.PublishedPath,
		&i.PublishedRevision,
		&i.PublishedRenderer,
		&i.PublishedBuild,
		&i.PublishedReceiptHash,
	)
	return i, err
}

const getAlbumByFingerprint = `-- name: GetAlbumByFingerprint :one
SELECT id, deleted_at FROM albums WHERE import_fingerprint = $1
`

type GetAlbumByFingerprintRow struct {
	ID        uuid.UUID
	DeletedAt *time.Time
}

func (q *Queries) GetAlbumByFingerprint(ctx context.Context, importFingerprint *string) (GetAlbumByFingerprintRow, error) {
	row := q.db.QueryRow(ctx, getAlbumByFingerprint, importFingerprint)
	var i GetAlbumByFingerprintRow
	err := row.Scan(&i.ID, &i.DeletedAt)
	return i, err
}

const getAlbumPathState = `-- name: GetAlbumPathState :one
SELECT (al.deleted_at IS NULL)::boolean AS active, al.title, ar.name AS artist_name, al.published_path
FROM albums al JOIN artists ar ON ar.id = al.artist_id
WHERE al.id = $1
`

type GetAlbumPathStateRow struct {
	Active        bool
	Title         string
	ArtistName    string
	PublishedPath *string
}

// What the path claims of an album are derived from (§5.3).
func (q *Queries) GetAlbumPathState(ctx context.Context, id uuid.UUID) (GetAlbumPathStateRow, error) {
	row := q.db.QueryRow(ctx, getAlbumPathState, id)
	var i GetAlbumPathStateRow
	err := row.Scan(
		&i.Active,
		&i.Title,
		&i.ArtistName,
		&i.PublishedPath,
	)
	return i, err
}

const getAlbumStatus = `-- name: GetAlbumStatus :one
SELECT al.id, al.revision, (al.deleted_at IS NOT NULL)::boolean AS trashed,
       al.published_path, al.published_revision, al.published_renderer,
       j.id AS job_id, j.state AS job_state, j.error_code AS job_error_code,
       j.error_message AS job_error_message, j.queued_at AS job_queued_at, j.updated_at AS job_updated_at
FROM albums al
LEFT JOIN jobs j ON j.kind = 'render' AND j.album_id = al.id
WHERE al.id = $1
`

type GetAlbumStatusRow struct {
	ID                uuid.UUID
	Revision          int64
	Trashed           bool
	PublishedPath     *string
	PublishedRevision int64
	PublishedRenderer *string
	JobID             *uuid.UUID
	JobState          *string
	JobErrorCode      *string
	JobErrorMessage   *string
	JobQueuedAt       *time.Time
	JobUpdatedAt      *time.Time
}

// The processing state (§10.2 GET /api/albums/{id}/status): revisions,
// published renderer and path (relative to library/), the render job.
func (q *Queries) GetAlbumStatus(ctx context.Context, id uuid.UUID) (GetAlbumStatusRow, error) {
	row := q.db.QueryRow(ctx, getAlbumStatus, id)
	var i GetAlbumStatusRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Trashed,
		&i.PublishedPath,
		&i.PublishedRevision,
		&i.PublishedRenderer,
		&i.JobID,
		&i.JobState,
		&i.JobErrorCode,
		&i.JobErrorMessage,
		&i.JobQueuedAt,
		&i.JobUpdatedAt,
	)
	return i, err
}

const getAlbumView = `-- name: GetAlbumView :one
SELECT al.id, al.artist_id, ar.name AS artist_name, al.title, al.year, al.genre, al.compilation,
       (al.deleted_at IS NOT NULL)::boolean AS trashed, al.revision,
       al.cover_hash, cb.size AS cover_size, cb.format AS cover_format
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN blobs cb ON cb.hash = al.cover_hash
WHERE al.id = $1
`

type GetAlbumViewRow struct {
	ID          uuid.UUID
	ArtistID    uuid.UUID
	ArtistName  string
	Title       string
	Year        *int32
	Genre       *string
	Compilation bool
	Trashed     bool
	Revision    int64
	CoverHash   *string
	CoverSize   *int64
	CoverFormat *string
}

// The desired album (§10.2 GET /api/albums/{id}): no published column.
func (q *Queries) GetAlbumView(ctx context.Context, id uuid.UUID) (GetAlbumViewRow, error) {
	row := q.db.QueryRow(ctx, getAlbumView, id)
	var i GetAlbumViewRow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.Title,
		&i.Year,
		&i.Genre,
		&i.Compilation,
		&i.Trashed,
		&i.Revision,
		&i.CoverHash,
		&i.CoverSize,
		&i.CoverFormat,
	)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, folder_key, revision FROM artists WHERE id = $1
`

// Artists (§4.3, §7.6).
func (q *Queries) GetArtist(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderKey,
		&i.Revision,
	)
	return i, err
}

const getArtistByFolderKey = `-- name: GetArtistByFolderKey :one
SELECT id, name, folder_key, revision FROM artists WHERE folder_key = $1
`

func (q *Queries) GetArtistByFolderKey(ctx context.Context, folderKey string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByFolderKey, folderKey)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FolderKey,
		&i.Revision,
	)
	return i, err
}

const getBlobs = `-- name: GetBlobs :many
SELECT hash, size, format FROM blobs WHERE hash = ANY($1::text[]) ORDER BY hash
`

type GetBlobsRow struct {
	Hash   string
	Size   int64
	Format *string
}

func (q *Queries) GetBlobs(ctx context.Context, hashes []string) ([]GetBlobsRow, error) {
	rows, err := q.db.Query(ctx, getBlobs, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlobsRow
	for rows.Next() {
		var i GetBlobsRow
		if err := rows.Scan(&i.Hash, &i.Size, &i.Format); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaims = `-- name: GetClaims :many
SELECT path_key, path, album_id FROM path_claims WHERE path_key = ANY($1::text[]) ORDER BY path_key
`

func (q *Queries) GetClaims(ctx context.Context, keys []string) ([]PathClaim, error) {
	rows, err := q.db.Query(ctx, getClaims, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PathClaim
	for rows.Next() {
		var i PathClaim
		if err := rows.Scan(&i.PathKey, &i.Path, &i.AlbumID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublication = `-- name: GetPublication :one
SELECT album_id, old_path, new_path FROM publication WHERE id = 1
`

type GetPublicationRow struct {
	AlbumID uuid.UUID
	OldPath *string
	NewPath *string
}

// The publication journal, zero or one row (§9.3).
func (q *Queries) GetPublication(ctx context.Context) (GetPublicationRow, error) {
	row := q.db.QueryRow(ctx, getPublication)
	var i GetPublicationRow
	err := row.Scan(&i.AlbumID, &i.OldPath, &i.NewPath)
	return i, err
}

const insertAlbum = `-- name: InsertAlbum :exec
INSERT INTO albums (id, artist_id, title, folder_key, year, genre, compilation, cover_hash, revision, import_fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 1, $9)
`

type InsertAlbumParams struct {
	ID                uuid.UUID
	ArtistID          uuid.UUID
	Title             string
	FolderKey         string
	Year              *int32
	Genre             *string
	Compilation       bool
	CoverHash         *string
	ImportFingerprint *string
}

func (q *Queries) InsertAlbum(ctx context.Context, arg InsertAlbumParams) error {
	_, err := q.db.Exec(ctx, insertAlbum,
		arg.ID,
		arg.ArtistID,
		arg.Title,
		arg.FolderKey,
		arg.Year,
		arg.Genre,
		arg.Compilation,
		arg.CoverHash,
		arg.ImportFingerprint,
	)
	return err
}

const insertArtist = `-- name: InsertArtist :exec
INSERT INTO artists (id, name, folder_key, revision) VALUES ($1, $2, $3, 1)
`

type InsertArtistParams struct {
	ID        uuid.UUID
	Name      string
	FolderKey string
}

func (q *Queries) InsertArtist(ctx context.Context, arg InsertArtistParams) error {
	_, err := q.db.Exec(ctx, insertArtist, arg.ID, arg.Name, arg.FolderKey)
	return err
}

type InsertAttachmentsParams struct {
	ID       uuid.UUID
	AlbumID  uuid.UUID
	RelPath  string
	PathKey  string
	BlobHash string
}

const insertBlobs = `-- name: InsertBlobs :exec
INSERT INTO blobs (hash, size, format, created_at)
SELECT u.hash, u.size, NULLIF(u.format, ''), now()
FROM (SELECT unnest($1::text[]) AS hash, unnest($2::bigint[]) AS size,
             unnest($3::text[]) AS format) AS u
ON CONFLICT (hash) DO NOTHING
`

type InsertBlobsParams struct {
	Hashes  []string
	Sizes   []int64
	Formats []string
}

// Blobs (§7.5, §7.6): the rows of blobs already pinned on disk. An existing
// row is kept; the caller compares size and format with GetBlobs.
func (q *Queries) InsertBlobs(ctx context.Context, arg InsertBlobsParams) error {
	_, err := q.db.Exec(ctx, insertBlobs, arg.Hashes, arg.Sizes, arg.Formats)
	return err
}

type InsertTracksParams struct {
	ID         uuid.UUID
	AlbumID    uuid.UUID
	Disc       int32
	No         int32
	Title      string
	Artist     *string
	Genre      *string
	BlobHash   string
	SourcePath string
	LyricsHash *string
}

const listAlbumAttachmentViews = `-- name: ListAlbumAttachmentViews :many
SELECT a.id, a.rel_path, a.blob_hash, b.size AS blob_size, b.format AS blob_format
FROM attachments a
JOIN blobs b ON b.hash = a.blob_hash
WHERE a.album_id = $1
ORDER BY a.path_key COLLATE "C", a.id
`

type ListAlbumAttachmentViewsRow struct {
	ID         uuid.UUID
	RelPath    string
	BlobHash   string
	BlobSize   int64
	BlobFormat *string
}

func (q *Queries) ListAlbumAttachmentViews(ctx context.Context, albumID uuid.UUID) ([]ListAlbumAttachmentViewsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumAttachmentViews, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumAttachmentViewsRow
	for rows.Next() {
		var i ListAlbumAttachmentViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumClaims = `-- name: ListAlbumClaims :many
SELECT path_key, path FROM path_claims WHERE album_id = $1 ORDER BY path_key
`

type ListAlbumClaimsRow struct {
	PathKey string
	Path    string
}

// Path claims (§5.3).
func (q *Queries) ListAlbumClaims(ctx context.Context, albumID uuid.UUID) ([]ListAlbumClaimsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumClaims, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumClaimsRow
	for rows.Next() {
		var i ListAlbumClaimsRow
		if err := rows.Scan(&i.PathKey, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTrackViews = `-- name: ListAlbumTrackViews :many
SELECT t.id, t.disc, t.no, t.title, t.artist, t.genre, t.source_path,
       t.blob_hash, b.size AS blob_size, b.format AS blob_format, t.lyrics_hash
FROM tracks t
JOIN blobs b ON b.hash = t.blob_hash
WHERE t.album_id = $1
ORDER BY t.disc, t.no, t.id
`

type ListAlbumTrackViewsRow struct {
	ID         uuid.UUID
	Disc       int32
	No         int32
	Title      string
	Artist     *string
	Genre      *string
	SourcePath string
	BlobHash   string
	BlobSize   int64
	BlobFormat *string
	LyricsHash *string
}

func (q *Queries) ListAlbumTrackViews(ctx context.Context, albumID uuid.UUID) ([]ListAlbumTrackViewsRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTrackViews, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTrackViewsRow
	for rows.Next() {
		var i ListAlbumTrackViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.SourcePath,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
			&i.LyricsHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTracks = `-- name: ListAlbumTracks :many
SELECT id, disc, no, title, artist, genre FROM tracks WHERE album_id = $1 ORDER BY disc, no, id
`

type ListAlbumTracksRow struct {
	ID     uuid.UUID
	Disc   int32
	No     int32
	Title  string
	Artist *string
	Genre  *string
}

func (q *Queries) ListAlbumTracks(ctx context.Context, albumID uuid.UUID) ([]ListAlbumTracksRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTracks, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTracksRow
	for rows.Next() {
		var i ListAlbumTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistAlbumIDs = `-- name: ListArtistAlbumIDs :many
SELECT id FROM albums WHERE artist_id = $1 ORDER BY id
`

// Every album of an artist, trashed ones included: a rename changes the
// tags and the folder of all of them (§4.3).
func (q *Queries) ListArtistAlbumIDs(ctx context.Context, artistID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listArtistAlbumIDs, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many

SELECT id, name, folder_key, revision FROM artists
ORDER BY folder_key COLLATE "C", id
`

// The API's reads (§10.1, §10.2). They run in one REPEATABLE READ snapshot
// (store.InSnapshotTx), so that a representation and its revision agree.
// Orders are deterministic and byte-wise (COLLATE "C"), independent of the
// database's locale.
// Every artist of the catalog, those without albums included (owner
// decision N-146: the list feeds the album editor's artist selector).
func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderKey,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCatalog = `-- name: LockCatalog :exec

SELECT pg_advisory_xact_lock(7884786317834415207)
`

// Catalog queries (DESIGN.md §4, §5.3, §7.6). Every statement here that
// writes runs inside store.InCatalogTx, under the catalog lock below.
// The catalog lock of §5.3: one transaction-scoped advisory lock with a
// constant key, taken first by every catalog mutation. The key is the ASCII
// "mlcatalg", distinct from the migration lock "mlmigrat" (N-053).
func (q *Queries) LockCatalog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCatalog)
	return err
}

const renameArtist = `-- name: RenameArtist :one
UPDATE artists SET name = $2, folder_key = $3, revision = revision + 1
WHERE id = $1
RETURNING revision
`

type RenameArtistParams struct {
	ID        uuid.UUID
	Name      string
	FolderKey string
}

func (q *Queries) RenameArtist(ctx context.Context, arg RenameArtistParams) (int64, error) {
	row := q.db.QueryRow(ctx, renameArtist, arg.ID, arg.Name, arg.FolderKey)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const setAlbumTrashed = `-- name: SetAlbumTrashed :exec
UPDATE albums SET deleted_at = CASE WHEN $1::boolean THEN now() END WHERE id = $2
`

type SetAlbumTrashedParams struct {
	Trashed bool
	ID      uuid.UUID
}

// Trash (deleted_at = now) or restore (deleted_at = NULL), §4.3.
func (q *Queries) SetAlbumTrashed(ctx context.Context, arg SetAlbumTrashedParams) error {
	_, err := q.db.Exec(ctx, setAlbumTrashed, arg.Trashed, arg.ID)
	return err
}

const setBlobFormat = `-- name: SetBlobFormat :execrows
UPDATE blobs SET format = $1 WHERE hash = $2 AND format IS NULL
`

type SetBlobFormatParams struct {
	Format *string
	Hash   string
}

// A content-derived format replaces "unknown", never another format.
func (q *Queries) SetBlobFormat(ctx context.Context, arg SetBlobFormatParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBlobFormat, arg.Format, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAlbumMetadata = `-- name: UpdateAlbumMetadata :exec
UPDATE albums
SET artist_id = $1, title = $2, folder_key = $3, year = $4,
    genre = $5, compilation = $6
WHERE id = $7
`

type UpdateAlbumMetadataParams struct {
	ArtistID    uuid.UUID
	Title       string
	FolderKey   string
	Year        *int32
	Genre       *string
	Compilation bool
	ID          uuid.UUID
}

func (q *Queries) UpdateAlbumMetadata(ctx context.Context, arg UpdateAlbumMetadataParams) error {
	_, err := q.db.Exec(ctx, updateAlbumMetadata,
		arg.ArtistID,
		arg.Title,
		arg.FolderKey,
		arg.Year,
		arg.Genre,
		arg.Compilation,
		arg.ID,
	)
	return err
}

const updateTrack = `-- name: UpdateTrack :execrows
UPDATE tracks SET disc = $1, no = $2, title = $3, artist = $4, genre = $5
WHERE id = $6 AND album_id = $7
`

type UpdateTrackParams struct {
	Disc    int32
	No      int32
	Title   string
	Artist  *string
	Genre   *string
	ID      uuid.UUID
	AlbumID uuid.UUID
}

// The (album_id, disc, no) constraint is deferred to the commit, so a swap
// of numbers needs no temporary values (§4.2, §12.2).
func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTrack,
		arg.Disc,
		arg.No,
		arg.Title,
		arg.Artist,
		arg.Genre,
		arg.ID,
		arg.AlbumID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertClaim = `-- name: UpsertClaim :execrows
INSERT INTO path_claims (path_key, path, album_id) VALUES ($1, $2, $3)
ON CONFLICT (path_key) DO UPDATE SET path = EXCLUDED.path
WHERE path_claims.album_id = EXCLUDED.album_id
`

type UpsertClaimParams struct {
	PathKey string
	Path    string
	AlbumID uuid.UUID
}

// Inserts a claim, or updates the display path of a claim the album already
// owns. Zero rows means another album owns the key.
func (q *Queries) UpsertClaim(ctx context.Context, arg UpsertClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertClaim, arg.PathKey, arg.Path, arg.AlbumID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
