// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertAttachments implements pgx.CopyFromSource.
type iteratorForInsertAttachments struct {
	rows                 []InsertAttachmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertAttachments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertAttachments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].AlbumID,
		r.rows[0].RelPath,
		r.rows[0].PathKey,
		r.rows[0].BlobHash,
	}, nil
}

func (r iteratorForInsertAttachments) Err() error {
	return nil
}

// Attachments (§4.2, §7.4). COPY for the same reason as tracks.
func (q *Queries) InsertAttachments(ctx context.Context, arg []InsertAttachmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attachments"}, []string{"id", "album_id", "rel_path", "path_key", "blob_hash"}, &iteratorForInsertAttachments{rows: arg})
}

// iteratorForInsertTracks implements pgx.CopyFromSource.
type iteratorForInsertTracks struct {
	rows                 []InsertTracksParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTracks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTracks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].AlbumID,
		r.rows[0].Disc,
		r.rows[0].No,
		r.rows[0].Title,
		r.rows[0].Artist,
		r.rows[0].Genre,
		r.rows[0].BlobHash,
		r.rows[0].SourcePath,
		r.rows[0].LyricsHash,
	}, nil
}

func (r iteratorForInsertTracks) Err() error {
	return nil
}

// Tracks (§4.2). COPY: an import writes up to 1,000 tracks (§7.2) in one
// short transaction.
func (q *Queries) InsertTracks(ctx context.Context, arg []InsertTracksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tracks"}, []string{"id", "album_id", "disc", "no", "title", "artist", "genre", "blob_hash", "source_path", "lyrics_hash"}, &iteratorForInsertTracks{rows: arg})
}
