// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteFinishedRender = `-- name: DeleteFinishedRender :execrows
DELETE FROM jobs
WHERE id = $1 AND kind = 'render' AND state = 'running' AND claimed = $2::bigint AND requested = $2::bigint
`

type DeleteFinishedRenderParams struct {
	ID     uuid.UUID
	Ticket int64
}

// §6.4: a render whose ticket is still the one built ends by disappearing.
func (q *Queries) DeleteFinishedRender(ctx context.Context, arg DeleteFinishedRenderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedRender, arg.ID, arg.Ticket)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueRender = `-- name: EnqueueRender :one

INSERT INTO jobs (id, kind, album_id, state, queued_at, updated_at)
VALUES ($1, 'render', $2, 'pending', now(), now())
ON CONFLICT (album_id) WHERE kind = 'render' DO UPDATE SET
    requested = nextval('job_ticket'),
    state = CASE WHEN jobs.state = 'running' THEN 'running' ELSE 'pending' END,
    error_code = NULL,
    error_message = NULL,
    queued_at = now(),
    updated_at = now()
RETURNING id, requested, claimed, state
`

type EnqueueRenderParams struct {
	ID      uuid.UUID
	AlbumID *uuid.UUID
}

type EnqueueRenderRow struct {
	ID        uuid.UUID
	Requested int64
	Claimed   *int64
	State     string
}

// The durable queue (DESIGN.md §6). Tickets are values of the job_ticket
// sequence; completions are conditioned on id, state running and the claimed
// ticket, so an old result can never complete a different attempt (§6.3).
// §6.3: the single enqueue of a render, an upsert on the album's one row.
// A running job stays running and keeps its claim: the new ticket says that
// more work follows the attempt in progress. Anything else becomes pending.
func (q *Queries) EnqueueRender(ctx context.Context, arg EnqueueRenderParams) (EnqueueRenderRow, error) {
	row := q.db.QueryRow(ctx, enqueueRender, arg.ID, arg.AlbumID)
	var i EnqueueRenderRow
	err := row.Scan(
		&i.ID,
		&i.Requested,
		&i.Claimed,
		&i.State,
	)
	return i, err
}

const failRenderAttempt = `-- name: FailRenderAttempt :one
UPDATE jobs SET
    state = CASE WHEN requested = claimed THEN 'failed' ELSE 'pending' END,
    error_code = CASE WHEN requested = claimed THEN $1::text END,
    error_message = CASE WHEN requested = claimed THEN $2::text END,
    claimed = NULL,
    updated_at = now()
WHERE id = $3 AND kind = 'render' AND state = 'running' AND claimed = $4::bigint
RETURNING state
`

type FailRenderAttemptParams struct {
	ErrorCode    string
	ErrorMessage string
	ID           uuid.UUID
	Ticket       int64
}

// §6.4: a render failed before the journal is failed only while its ticket
// is current; otherwise the newer request stays pending, without the error.
func (q *Queries) FailRenderAttempt(ctx context.Context, arg FailRenderAttemptParams) (string, error) {
	row := q.db.QueryRow(ctx, failRenderAttempt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.Ticket,
	)
	var state string
	err := row.Scan(&state)
	return state, err
}

const finishAttempt = `-- name: FinishAttempt :execrows
UPDATE jobs SET
    state = $1,
    claimed = NULL,
    result_album_id = $2,
    error_code = $3,
    error_message = $4,
    warnings = $5,
    updated_at = now()
WHERE id = $6 AND kind = $7 AND state = 'running' AND claimed = $8::bigint
`

type FinishAttemptParams struct {
	State         string
	ResultAlbumID *uuid.UUID
	ErrorCode     *string
	ErrorMessage  *string
	Warnings      []byte
	ID            uuid.UUID
	Kind          string
	Ticket        int64
}

// §6.4: the outcome of a scan or an import, kept for the report.
func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAttempt,
		arg.State,
		arg.ResultAlbumID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Warnings,
		arg.ID,
		arg.Kind,
		arg.Ticket,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, root_rel, created_at FROM import_batches WHERE id = $1
`

func (q *Queries) GetImportBatch(ctx context.Context, id uuid.UUID) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, id)
	var i ImportBatch
	err := row.Scan(&i.ID, &i.RootRel, &i.CreatedAt)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
		&i.Claimed,
		&i.State,
		&i.ResultAlbumID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Warnings,
		&i.QueuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobForUpdate = `-- name: GetJobForUpdate :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at FROM jobs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetJobForUpdate(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobForUpdate, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
		&i.Claimed,
		&i.State,
		&i.ResultAlbumID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Warnings,
		&i.QueuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, state FROM jobs WHERE kind = 'scan' AND batch_id = $1
`

type GetScanJobRow struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) GetScanJob(ctx context.Context, batchID *uuid.UUID) (GetScanJobRow, error) {
	row := q.db.QueryRow(ctx, getScanJob, batchID)
	var i GetScanJobRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const insertImportBatch = `-- name: InsertImportBatch :exec
INSERT INTO import_batches (id, root_rel, created_at) VALUES ($1, $2, now())
ON CONFLICT (id) DO NOTHING
`

type InsertImportBatchParams struct {
	ID      uuid.UUID
	RootRel string
}

// §7.1: the import batch behind POST /api/imports. The id is the client's
// idempotency key; an existing batch is kept and compared by the caller.
func (q *Queries) InsertImportBatch(ctx context.Context, arg InsertImportBatchParams) error {
	_, err := q.db.Exec(ctx, insertImportBatch, arg.ID, arg.RootRel)
	return err
}

const insertImportJob = `-- name: InsertImportJob :execrows
INSERT INTO jobs (id, kind, batch_id, source_rel, state, error_code, error_message, queued_at, updated_at)
VALUES ($1, 'import', $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (batch_id, source_rel) WHERE kind = 'import' DO NOTHING
`

type InsertImportJobParams struct {
	ID           uuid.UUID
	BatchID      *uuid.UUID
	SourceRel    *string
	State        string
	ErrorCode    *string
	ErrorMessage *string
}

// §7.2: an import job found by the scan, pending, or already failed for an
// ambiguous branch. (batch_id, source_rel) is unique, so a scan repeated
// after a crash inserts nothing twice.
func (q *Queries) InsertImportJob(ctx context.Context, arg InsertImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertImportJob,
		arg.ID,
		arg.BatchID,
		arg.SourceRel,
		arg.State,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertScanJob = `-- name: InsertScanJob :exec
INSERT INTO jobs (id, kind, batch_id, state, queued_at, updated_at)
VALUES ($1, 'scan', $2, 'pending', now(), now())
ON CONFLICT (batch_id) WHERE kind = 'scan' DO NOTHING
`

type InsertScanJobParams struct {
	ID      uuid.UUID
	BatchID *uuid.UUID
}

// §7.1: the one scan job of a batch (jobs_scan_batch_key).
func (q *Queries) InsertScanJob(ctx context.Context, arg InsertScanJobParams) error {
	_, err := q.db.Exec(ctx, insertScanJob, arg.ID, arg.BatchID)
	return err
}

const listStaleRenderAlbums = `-- name: ListStaleRenderAlbums :many
SELECT al.id FROM albums al
WHERE al.deleted_at IS NULL
  AND al.published_renderer IS DISTINCT FROM $1::text
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'render' AND j.album_id = al.id)
ORDER BY al.id
`

// §11.1 step 6: active albums whose published renderer is not the current
// one (never published included) and that have no render job at all: a
// failed job stays explicit.
func (q *Queries) ListStaleRenderAlbums(ctx context.Context, renderer string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleRenderAlbums, renderer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunning = `-- name: MarkJobRunning :one
UPDATE jobs SET state = 'running', claimed = requested, updated_at = now()
WHERE id = $1 AND state = 'pending'
RETURNING requested
`

func (q *Queries) MarkJobRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, markJobRunning, id)
	var requested int64
	err := row.Scan(&requested)
	return requested, err
}

const nextPendingJob = `-- name: NextPendingJob :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested
FROM jobs
WHERE state = 'pending' AND kind = $1
ORDER BY queued_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type NextPendingJobRow struct {
	ID        uuid.UUID
	Kind      string
	AlbumID   *uuid.UUID
	BatchID   *uuid.UUID
	SourceRel *string
	Overrides []byte
	Requested int64
}

// §6.2: the oldest pending job of one kind, skipping rows another
// transaction holds. The caller asks render, then scan, then import (§6.1).
func (q *Queries) NextPendingJob(ctx context.Context, kind string) (NextPendingJobRow, error) {
	row := q.db.QueryRow(ctx, nextPendingJob, kind)
	var i NextPendingJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
	)
	return i, err
}

const recoverRunningJobs = `-- name: RecoverRunningJobs :execrows
UPDATE jobs SET state = 'pending', claimed = NULL, updated_at = now()
WHERE state = 'running'
`

// §6.4, §11.1 step 5: after the journal is recovered, no attempt of the
// previous process is still running.
func (q *Queries) RecoverRunningJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverRunningJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueRenderAttempt = `-- name: RequeueRenderAttempt :execrows
UPDATE jobs SET state = 'pending', claimed = NULL, updated_at = now()
WHERE id = $1 AND kind = 'render' AND state = 'running' AND claimed = $2::bigint
`

type RequeueRenderAttemptParams struct {
	ID     uuid.UUID
	Ticket int64
}

// §6.3, §6.4: a render attempt goes back to pending (a newer request exists, or
// the work was superseded before PREPARE). Leaving running clears claimed.
func (q *Queries) RequeueRenderAttempt(ctx context.Context, arg RequeueRenderAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueRenderAttempt, arg.ID, arg.Ticket)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotAlbum = `-- name: SnapshotAlbum :one
SELECT al.id, al.title, al.year, al.genre, al.compilation, al.revision,
       (al.deleted_at IS NOT NULL)::boolean AS deleted,
       al.published_path, al.published_revision, al.published_renderer,
       al.published_build, al.published_receipt_hash,
       ar.id AS artist_id, ar.name AS artist_name, ar.revision AS artist_revision,
       al.cover_hash, cb.size AS cover_size, cb.format AS cover_format
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN blobs cb ON cb.hash = al.cover_hash
WHERE al.id = $1
`

type SnapshotAlbumRow struct {
	ID                   uuid.UUID
	Title                string
	Year                 *int32
	Genre                *string
	Compilation          bool
	Revision             int64
	Deleted              bool
	PublishedPath        *string
	PublishedRevision    int64
	PublishedRenderer    *string
	PublishedBuild       *uuid.UUID
	PublishedReceiptHash *string
	ArtistID             uuid.UUID
	ArtistName           string
	ArtistRevision       int64
	CoverHash            *string
	CoverSize            *int64
	CoverFormat          *string
}

// The render snapshot (§6.2), read in the claim's REPEATABLE READ
// transaction.
func (q *Queries) SnapshotAlbum(ctx context.Context, id uuid.UUID) (SnapshotAlbumRow, error) {
	row := q.db.QueryRow(ctx, snapshotAlbum, id)
	var i SnapshotAlbumRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Genre,
		&i.Compilation,
		&i.Revision,
		&i.Deleted,
		&i.PublishedPath,
		&i.PublishedRevision,
		&i.PublishedRenderer,
		&i.PublishedBuild,
		&i.PublishedReceiptHash,
		&i.ArtistID,
		&i.ArtistName,
		&i.ArtistRevision,
		&i.CoverHash,
		&i.CoverSize,
		&i.CoverFormat,
	)
	return i, err
}

const snapshotAttachments = `-- name: SnapshotAttachments :many
SELECT a.id, a.rel_path, a.path_key, a.blob_hash, b.size AS blob_size, b.format AS blob_format
FROM attachments a
JOIN blobs b ON b.hash = a.blob_hash
WHERE a.album_id = $1
ORDER BY a.path_key
`

type SnapshotAttachmentsRow struct {
	ID         uuid.UUID
	RelPath    string
	PathKey    string
	BlobHash   string
	BlobSize   int64
	BlobFormat *string
}

func (q *Queries) SnapshotAttachments(ctx context.Context, albumID uuid.UUID) ([]SnapshotAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, snapshotAttachments, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotAttachmentsRow
	for rows.Next() {
		var i SnapshotAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.PathKey,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTracks = `-- name: SnapshotTracks :many
SELECT t.id, t.disc, t.no, t.title, t.artist, t.genre, t.source_path,
       t.blob_hash, b.size AS blob_size, b.format AS blob_format,
       t.lyrics_hash, lb.size AS lyrics_size
FROM tracks t
JOIN blobs b ON b.hash = t.blob_hash
LEFT JOIN blobs lb ON lb.hash = t.lyrics_hash
WHERE t.album_id = $1
ORDER BY t.disc, t.no
`

type SnapshotTracksRow struct {
	ID         uuid.UUID
	Disc       int32
	No         int32
	Title      string
	Artist     *string
	Genre      *string
	SourcePath string
	BlobHash   string
	BlobSize   int64
	BlobFormat *string
	LyricsHash *string
	LyricsSize *int64
}

func (q *Queries) SnapshotTracks(ctx context.Context, albumID uuid.UUID) ([]SnapshotTracksRow, error) {
	rows, err := q.db.Query(ctx, snapshotTracks, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotTracksRow
	for rows.Next() {
		var i SnapshotTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.SourcePath,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
			&i.LyricsHash,
			&i.LyricsSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
