// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRenderAllAlbums = `-- name: CountRenderAllAlbums :one
SELECT count(*)::bigint AS albums FROM albums
WHERE deleted_at IS NULL OR published_path IS NOT NULL
`

// How many albums POST /api/render-all enqueues (ListRenderAllAlbums): the
// confirmation of «Rebuild the library folder» says it (NOTES.md N-289).
func (q *Queries) CountRenderAllAlbums(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRenderAllAlbums)
	var albums int64
	err := row.Scan(&albums)
	return albums, err
}

const deleteBatchJobs = `-- name: DeleteBatchJobs :execrows
DELETE FROM jobs WHERE batch_id = ANY($1::uuid[])
`

func (q *Queries) DeleteBatchJobs(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBatchJobs, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFinishedRender = `-- name: DeleteFinishedRender :execrows
DELETE FROM jobs
WHERE id = $1 AND kind = 'render' AND state = 'running' AND claimed = $2::bigint AND requested = $2::bigint
`

type DeleteFinishedRenderParams struct {
	ID     uuid.UUID
	Ticket int64
}

// §6.4: a render whose ticket is still the one built ends by disappearing.
func (q *Queries) DeleteFinishedRender(ctx context.Context, arg DeleteFinishedRenderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedRender, arg.ID, arg.Ticket)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteImportBatches = `-- name: DeleteImportBatches :execrows
DELETE FROM import_batches WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteImportBatches(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteImportBatches, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissFailedJob = `-- name: DismissFailedJob :execrows
UPDATE jobs SET dismissed_at = coalesce(dismissed_at, now())
WHERE id = $1 AND kind IN ('scan', 'import') AND state = 'failed'
`

// The user dismisses a failed scan or import (NOTES.md N-285): it stops
// needing attention. Its state, outcome, ticket and updated_at stay, so
// the retention of §6.4 is unchanged. A second dismissal keeps the first
// time.
func (q *Queries) DismissFailedJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, dismissFailedJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueRender = `-- name: EnqueueRender :one

INSERT INTO jobs (id, kind, album_id, state, queued_at, updated_at)
VALUES ($1, 'render', $2, 'pending', now(), now())
ON CONFLICT (album_id) WHERE kind = 'render' DO UPDATE SET
    requested = nextval('job_ticket'),
    state = CASE WHEN jobs.state = 'running' THEN 'running' ELSE 'pending' END,
    error_code = NULL,
    error_message = NULL,
    queued_at = now(),
    updated_at = now()
RETURNING id, requested, claimed, state
`

type EnqueueRenderParams struct {
	ID      uuid.UUID
	AlbumID *uuid.UUID
}

type EnqueueRenderRow struct {
	ID        uuid.UUID
	Requested int64
	Claimed   *int64
	State     string
}

// The durable queue (DESIGN.md §6). Tickets are values of the job_ticket
// sequence; completions are conditioned on id, state running and the claimed
// ticket, so an old result can never complete a different attempt (§6.3).
// §6.3: the single enqueue of a render, an upsert on the album's one row.
// A running job stays running and keeps its claim: the new ticket says that
// more work follows the attempt in progress. Anything else becomes pending.
func (q *Queries) EnqueueRender(ctx context.Context, arg EnqueueRenderParams) (EnqueueRenderRow, error) {
	row := q.db.QueryRow(ctx, enqueueRender, arg.ID, arg.AlbumID)
	var i EnqueueRenderRow
	err := row.Scan(
		&i.ID,
		&i.Requested,
		&i.Claimed,
		&i.State,
	)
	return i, err
}

const failRenderAttempt = `-- name: FailRenderAttempt :one
UPDATE jobs SET
    state = CASE WHEN requested = claimed THEN 'failed' ELSE 'pending' END,
    error_code = CASE WHEN requested = claimed THEN $1::text END,
    error_message = CASE WHEN requested = claimed THEN $2::text END,
    claimed = NULL,
    updated_at = now()
WHERE id = $3 AND kind = 'render' AND state = 'running' AND claimed = $4::bigint
RETURNING state
`

type FailRenderAttemptParams struct {
	ErrorCode    string
	ErrorMessage string
	ID           uuid.UUID
	Ticket       int64
}

// §6.4: a render failed before the journal is failed only while its ticket
// is current; otherwise the newer request stays pending, without the error.
func (q *Queries) FailRenderAttempt(ctx context.Context, arg FailRenderAttemptParams) (string, error) {
	row := q.db.QueryRow(ctx, failRenderAttempt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.Ticket,
	)
	var state string
	err := row.Scan(&state)
	return state, err
}

const finishAttempt = `-- name: FinishAttempt :execrows
UPDATE jobs SET
    state = $1,
    claimed = NULL,
    result_album_id = $2,
    error_code = $3,
    error_message = $4,
    warnings = $5,
    updated_at = now()
WHERE id = $6 AND kind = $7 AND state = 'running' AND claimed = $8::bigint
`

type FinishAttemptParams struct {
	State         string
	ResultAlbumID *uuid.UUID
	ErrorCode     *string
	ErrorMessage  *string
	Warnings      []byte
	ID            uuid.UUID
	Kind          string
	Ticket        int64
}

// §6.4: the outcome of a scan or an import, kept for the report.
func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAttempt,
		arg.State,
		arg.ResultAlbumID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Warnings,
		arg.ID,
		arg.Kind,
		arg.Ticket,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBatchScanJob = `-- name: GetBatchScanJob :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at, dismissed_at FROM jobs WHERE kind = 'scan' AND batch_id = $1
`

func (q *Queries) GetBatchScanJob(ctx context.Context, batchID *uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getBatchScanJob, batchID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
		&i.Claimed,
		&i.State,
		&i.ResultAlbumID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Warnings,
		&i.QueuedAt,
		&i.UpdatedAt,
		&i.DismissedAt,
	)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, root_rel, created_at FROM import_batches WHERE id = $1
`

func (q *Queries) GetImportBatch(ctx context.Context, id uuid.UUID) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, id)
	var i ImportBatch
	err := row.Scan(&i.ID, &i.RootRel, &i.CreatedAt)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at, dismissed_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
		&i.Claimed,
		&i.State,
		&i.ResultAlbumID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Warnings,
		&i.QueuedAt,
		&i.UpdatedAt,
		&i.DismissedAt,
	)
	return i, err
}

const getJobForUpdate = `-- name: GetJobForUpdate :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at, dismissed_at FROM jobs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetJobForUpdate(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobForUpdate, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
		&i.Claimed,
		&i.State,
		&i.ResultAlbumID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Warnings,
		&i.QueuedAt,
		&i.UpdatedAt,
		&i.DismissedAt,
	)
	return i, err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, state FROM jobs WHERE kind = 'scan' AND batch_id = $1
`

type GetScanJobRow struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) GetScanJob(ctx context.Context, batchID *uuid.UUID) (GetScanJobRow, error) {
	row := q.db.QueryRow(ctx, getScanJob, batchID)
	var i GetScanJobRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const insertImportBatch = `-- name: InsertImportBatch :exec
INSERT INTO import_batches (id, root_rel, created_at) VALUES ($1, $2, now())
ON CONFLICT (id) DO NOTHING
`

type InsertImportBatchParams struct {
	ID      uuid.UUID
	RootRel string
}

// §7.1: the import batch behind POST /api/imports. The id is the client's
// idempotency key; an existing batch is kept and compared by the caller.
func (q *Queries) InsertImportBatch(ctx context.Context, arg InsertImportBatchParams) error {
	_, err := q.db.Exec(ctx, insertImportBatch, arg.ID, arg.RootRel)
	return err
}

const insertImportJob = `-- name: InsertImportJob :execrows
INSERT INTO jobs (id, kind, batch_id, source_rel, state, error_code, error_message, queued_at, updated_at)
VALUES ($1, 'import', $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (batch_id, source_rel) WHERE kind = 'import' DO NOTHING
`

type InsertImportJobParams struct {
	ID           uuid.UUID
	BatchID      *uuid.UUID
	SourceRel    *string
	State        string
	ErrorCode    *string
	ErrorMessage *string
}

// §7.2: an import job found by the scan, pending, or already failed for an
// ambiguous branch. (batch_id, source_rel) is unique, so a scan repeated
// after a crash inserts nothing twice.
func (q *Queries) InsertImportJob(ctx context.Context, arg InsertImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertImportJob,
		arg.ID,
		arg.BatchID,
		arg.SourceRel,
		arg.State,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertScanJob = `-- name: InsertScanJob :exec
INSERT INTO jobs (id, kind, batch_id, state, queued_at, updated_at)
VALUES ($1, 'scan', $2, 'pending', now(), now())
ON CONFLICT (batch_id) WHERE kind = 'scan' DO NOTHING
`

type InsertScanJobParams struct {
	ID      uuid.UUID
	BatchID *uuid.UUID
}

// §7.1: the one scan job of a batch (jobs_scan_batch_key).
func (q *Queries) InsertScanJob(ctx context.Context, arg InsertScanJobParams) error {
	_, err := q.db.Exec(ctx, insertScanJob, arg.ID, arg.BatchID)
	return err
}

const jobAttention = `-- name: JobAttention :many
SELECT id, job_superseded(id)::boolean AS superseded, job_needs_attention(id)::boolean AS attention
FROM jobs WHERE id = ANY($1::uuid[])
`

type JobAttentionRow struct {
	ID         uuid.UUID
	Superseded bool
	Attention  bool
}

// Whether each job is superseded and whether it needs attention (the
// functions of migration 00002, NOTES.md N-285), for the API's job
// representation.
func (q *Queries) JobAttention(ctx context.Context, ids []uuid.UUID) ([]JobAttentionRow, error) {
	rows, err := q.db.Query(ctx, jobAttention, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobAttentionRow
	for rows.Next() {
		var i JobAttentionRow
		if err := rows.Scan(&i.ID, &i.Superseded, &i.Attention); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivity = `-- name: ListActivity :many
WITH listed AS (
    SELECT j.id, j.kind, j.state, j.requested, j.album_id, j.batch_id,
           coalesce(j.source_rel, b.root_rel, '') AS folder,
           j.error_code, j.error_message, j.queued_at, j.updated_at,
           al.title AS album_title, ar.name AS artist_name,
           (al.cover_hash IS NOT NULL) AS has_cover, (al.deleted_at IS NOT NULL) AS trashed
    FROM jobs j
    LEFT JOIN import_batches b ON b.id = j.batch_id
    LEFT JOIN albums al ON al.id = j.album_id
    LEFT JOIN artists ar ON ar.id = al.artist_id
    WHERE j.state IN ('pending', 'running') OR (j.state = 'failed' AND job_needs_attention(j.id))
), ranked AS (
    SELECT listed.id, listed.kind, listed.state, listed.requested, listed.album_id, listed.batch_id, listed.folder, listed.error_code, listed.error_message, listed.queued_at, listed.updated_at, listed.album_title, listed.artist_name, listed.has_cover, listed.trashed,
           count(*) OVER (PARTITION BY state) AS state_total,
           row_number() OVER (PARTITION BY state
               ORDER BY CASE WHEN state = 'failed' THEN updated_at END DESC, queued_at, id) AS state_rank
    FROM listed
)
SELECT id, kind, state, requested, album_id, batch_id, folder, error_code, error_message,
       queued_at, updated_at, album_title, artist_name,
       coalesce(has_cover, false)::boolean AS has_cover, coalesce(trashed, false)::boolean AS trashed,
       state_total::bigint AS state_total
FROM ranked
WHERE state_rank <= $1::bigint
ORDER BY state, state_rank
`

type ListActivityRow struct {
	ID           uuid.UUID
	Kind         string
	State        string
	Requested    int64
	AlbumID      *uuid.UUID
	BatchID      *uuid.UUID
	Folder       string
	ErrorCode    *string
	ErrorMessage *string
	QueuedAt     time.Time
	UpdatedAt    time.Time
	AlbumTitle   *string
	ArtistName   *string
	HasCover     bool
	Trashed      bool
	StateTotal   int64
}

// The Activity view (NOTES.md N-289): the jobs in progress, waiting and
// needing attention, at most @per_state of each with each state's total;
// in progress and waiting in queue order, needing attention newest first.
// A scan or an import names its folder (the candidate, or the batch root),
// a render its album.
func (q *Queries) ListActivity(ctx context.Context, perState int64) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity, perState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityRow
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.State,
			&i.Requested,
			&i.AlbumID,
			&i.BatchID,
			&i.Folder,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.QueuedAt,
			&i.UpdatedAt,
			&i.AlbumTitle,
			&i.ArtistName,
			&i.HasCover,
			&i.Trashed,
			&i.StateTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchImportJobs = `-- name: ListBatchImportJobs :many
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at, dismissed_at FROM jobs WHERE kind = 'import' AND batch_id = $1
ORDER BY source_rel COLLATE "C", id
`

// The candidates of a batch (§7.2), by the bytes of their path.
func (q *Queries) ListBatchImportJobs(ctx context.Context, batchID *uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listBatchImportJobs, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AlbumID,
			&i.BatchID,
			&i.SourceRel,
			&i.Overrides,
			&i.Requested,
			&i.Claimed,
			&i.State,
			&i.ResultAlbumID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Warnings,
			&i.QueuedAt,
			&i.UpdatedAt,
			&i.DismissedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredBatches = `-- name: ListExpiredBatches :many
SELECT b.id FROM import_batches b
WHERE b.created_at < now() - make_interval(days => $1::int)
  AND NOT EXISTS (
    SELECT 1 FROM jobs j
    WHERE j.batch_id = b.id
      AND (j.state IN ('pending', 'running') OR j.updated_at >= now() - make_interval(days => $1::int)))
ORDER BY b.id
`

// §6.4 retention: "Esiti conservati 90 giorni; non si eliminano batch con
// job non terminali". A batch expires when it and every one of its jobs
// are older than the retention, and none of its jobs is pending or
// running. Run under the catalog lock, which every transition of a
// terminal job back to pending also holds (retry, scan commit).
func (q *Queries) ListExpiredBatches(ctx context.Context, days int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredBatches, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedRenderAlbums = `-- name: ListFailedRenderAlbums :many
SELECT al.id FROM jobs j JOIN albums al ON al.id = j.album_id
WHERE j.kind = 'render' AND j.state = 'failed'
ORDER BY al.id
`

// The albums of the failed renders, for retry-failed: each is enqueued
// again through the single enqueue (§6.3).
func (q *Queries) ListFailedRenderAlbums(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFailedRenderAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at, dismissed_at FROM jobs
WHERE state = ANY($1::text[]) AND kind = ANY($2::text[]) AND id > $3::uuid
ORDER BY id
LIMIT $4::int
`

type ListJobsParams struct {
	States []string
	Kinds  []string
	After  uuid.UUID
	Lim    int32
}

// The API's reads of the queue (§10.2 GET /api/jobs, GET /api/imports/{id}).
// They run in one REPEATABLE READ snapshot (store.InSnapshotTx). Jobs are
// listed by id: a UUIDv7 never changes, so a page boundary never moves
// when a job changes state (NOTES.md N-194).
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.States,
		arg.Kinds,
		arg.After,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AlbumID,
			&i.BatchID,
			&i.SourceRel,
			&i.Overrides,
			&i.Requested,
			&i.Claimed,
			&i.State,
			&i.ResultAlbumID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Warnings,
			&i.QueuedAt,
			&i.UpdatedAt,
			&i.DismissedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentImports = `-- name: ListRecentImports :many
SELECT b.id, b.root_rel, b.created_at,
       count(*) FILTER (WHERE j.state IN ('pending', 'running'))::bigint AS active,
       count(*) FILTER (WHERE j.kind = 'import' AND j.state = 'done')::bigint AS imported,
       count(*) FILTER (WHERE j.kind = 'import' AND j.state = 'skipped')::bigint AS present,
       count(*) FILTER (WHERE j.state = 'failed' AND job_needs_attention(j.id))::bigint AS attention
FROM import_batches b
JOIN jobs j ON j.batch_id = b.id
GROUP BY b.id
ORDER BY b.created_at DESC, b.id DESC
`

type ListRecentImportsRow struct {
	ID        uuid.UUID
	RootRel   string
	CreatedAt time.Time
	Active    int64
	Imported  int64
	Present   int64
	Attention int64
}

// The import batches for «Recent imports» (NOTES.md N-288), newest first,
// with how many of their jobs are in progress, imported, already there and
// needing attention. Every batch is kept 90 days (§6.4).
func (q *Queries) ListRecentImports(ctx context.Context) ([]ListRecentImportsRow, error) {
	rows, err := q.db.Query(ctx, listRecentImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentImportsRow
	for rows.Next() {
		var i ListRecentImportsRow
		if err := rows.Scan(
			&i.ID,
			&i.RootRel,
			&i.CreatedAt,
			&i.Active,
			&i.Imported,
			&i.Present,
			&i.Attention,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenderAllAlbums = `-- name: ListRenderAllAlbums :many
SELECT id FROM albums
WHERE deleted_at IS NULL OR published_path IS NOT NULL
ORDER BY id
`

// §10.2 POST /api/render-all: every active album, and every trashed album
// whose output is still published (a deletion still to materialize).
func (q *Queries) ListRenderAllAlbums(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRenderAllAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRenderAlbums = `-- name: ListStaleRenderAlbums :many
SELECT al.id FROM albums al
WHERE al.deleted_at IS NULL
  AND al.published_renderer IS DISTINCT FROM $1::text
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'render' AND j.album_id = al.id)
ORDER BY al.id
`

// §11.1 step 6: active albums whose published renderer is not the current
// one (never published included) and that have no render job at all: a
// failed job stays explicit.
func (q *Queries) ListStaleRenderAlbums(ctx context.Context, renderer string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleRenderAlbums, renderer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunning = `-- name: MarkJobRunning :one
UPDATE jobs SET state = 'running', claimed = requested, updated_at = now()
WHERE id = $1 AND state = 'pending'
RETURNING requested
`

func (q *Queries) MarkJobRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, markJobRunning, id)
	var requested int64
	err := row.Scan(&requested)
	return requested, err
}

const nextPendingJob = `-- name: NextPendingJob :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested
FROM jobs
WHERE state = 'pending' AND kind = $1
ORDER BY queued_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type NextPendingJobRow struct {
	ID        uuid.UUID
	Kind      string
	AlbumID   *uuid.UUID
	BatchID   *uuid.UUID
	SourceRel *string
	Overrides []byte
	Requested int64
}

// §6.2: the oldest pending job of one kind, skipping rows another
// transaction holds. The caller asks render, then scan, then import (§6.1).
func (q *Queries) NextPendingJob(ctx context.Context, kind string) (NextPendingJobRow, error) {
	row := q.db.QueryRow(ctx, nextPendingJob, kind)
	var i NextPendingJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
	)
	return i, err
}

const recoverRunningJobs = `-- name: RecoverRunningJobs :execrows
UPDATE jobs SET state = 'pending', claimed = NULL, updated_at = now()
WHERE state = 'running'
`

// §6.4, §11.1 step 5: after the journal is recovered, no attempt of the
// previous process is still running.
func (q *Queries) RecoverRunningJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverRunningJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueRenderAttempt = `-- name: RequeueRenderAttempt :execrows
UPDATE jobs SET state = 'pending', claimed = NULL, updated_at = now()
WHERE id = $1 AND kind = 'render' AND state = 'running' AND claimed = $2::bigint
`

type RequeueRenderAttemptParams struct {
	ID     uuid.UUID
	Ticket int64
}

// §6.3, §6.4: a render attempt goes back to pending (a newer request exists, or
// the work was superseded before PREPARE). Leaving running clears claimed.
func (q *Queries) RequeueRenderAttempt(ctx context.Context, arg RequeueRenderAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueRenderAttempt, arg.ID, arg.Ticket)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryAllFailedJobs = `-- name: RetryAllFailedJobs :execrows
UPDATE jobs SET
    state = 'pending',
    claimed = NULL,
    requested = nextval('job_ticket'),
    result_album_id = NULL,
    error_code = NULL,
    error_message = NULL,
    warnings = '[]',
    queued_at = now(),
    updated_at = now()
WHERE kind IN ('scan', 'import') AND state = 'failed' AND job_needs_attention(id)
`

// §10.2 POST /api/jobs/retry-failed, the scans and imports: every failed
// one that still needs attention gets a new ticket and keeps its
// overrides; a dismissed or superseded one is left as it is (NOTES.md
// N-285), and nothing else is touched, a running job least of all.
func (q *Queries) RetryAllFailedJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, retryAllFailedJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryFailedJob = `-- name: RetryFailedJob :one
UPDATE jobs SET
    state = 'pending',
    claimed = NULL,
    requested = nextval('job_ticket'),
    overrides = $1,
    result_album_id = NULL,
    error_code = NULL,
    error_message = NULL,
    warnings = '[]',
    dismissed_at = NULL,
    queued_at = now(),
    updated_at = now()
WHERE id = $2 AND kind IN ('scan', 'import') AND state = 'failed'
RETURNING requested
`

type RetryFailedJobParams struct {
	Overrides []byte
	ID        uuid.UUID
}

// §10.2 retry of a failed scan or import: a new ticket, back to pending,
// the outcome of the failed attempt cleared; the overrides are the
// caller's (the stored ones, or new ones for an import, §7.3). A new
// attempt is no longer dismissed (NOTES.md N-285).
func (q *Queries) RetryFailedJob(ctx context.Context, arg RetryFailedJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, retryFailedJob, arg.Overrides, arg.ID)
	var requested int64
	err := row.Scan(&requested)
	return requested, err
}

const snapshotAlbum = `-- name: SnapshotAlbum :one
SELECT al.id, al.title, al.year, al.genre, al.compilation, al.revision,
       (al.deleted_at IS NOT NULL)::boolean AS deleted,
       al.published_path, al.published_revision, al.published_renderer,
       al.published_build, al.published_receipt_hash,
       ar.id AS artist_id, ar.name AS artist_name, ar.revision AS artist_revision,
       al.cover_hash, cb.size AS cover_size, cb.format AS cover_format
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN blobs cb ON cb.hash = al.cover_hash
WHERE al.id = $1
`

type SnapshotAlbumRow struct {
	ID                   uuid.UUID
	Title                string
	Year                 *int32
	Genre                *string
	Compilation          bool
	Revision             int64
	Deleted              bool
	PublishedPath        *string
	PublishedRevision    int64
	PublishedRenderer    *string
	PublishedBuild       *uuid.UUID
	PublishedReceiptHash *string
	ArtistID             uuid.UUID
	ArtistName           string
	ArtistRevision       int64
	CoverHash            *string
	CoverSize            *int64
	CoverFormat          *string
}

// The render snapshot (§6.2), read in the claim's REPEATABLE READ
// transaction.
func (q *Queries) SnapshotAlbum(ctx context.Context, id uuid.UUID) (SnapshotAlbumRow, error) {
	row := q.db.QueryRow(ctx, snapshotAlbum, id)
	var i SnapshotAlbumRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Genre,
		&i.Compilation,
		&i.Revision,
		&i.Deleted,
		&i.PublishedPath,
		&i.PublishedRevision,
		&i.PublishedRenderer,
		&i.PublishedBuild,
		&i.PublishedReceiptHash,
		&i.ArtistID,
		&i.ArtistName,
		&i.ArtistRevision,
		&i.CoverHash,
		&i.CoverSize,
		&i.CoverFormat,
	)
	return i, err
}

const snapshotAttachments = `-- name: SnapshotAttachments :many
SELECT a.id, a.rel_path, a.path_key, a.blob_hash, b.size AS blob_size, b.format AS blob_format
FROM attachments a
JOIN blobs b ON b.hash = a.blob_hash
WHERE a.album_id = $1
ORDER BY a.path_key
`

type SnapshotAttachmentsRow struct {
	ID         uuid.UUID
	RelPath    string
	PathKey    string
	BlobHash   string
	BlobSize   int64
	BlobFormat *string
}

func (q *Queries) SnapshotAttachments(ctx context.Context, albumID uuid.UUID) ([]SnapshotAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, snapshotAttachments, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotAttachmentsRow
	for rows.Next() {
		var i SnapshotAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.PathKey,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTracks = `-- name: SnapshotTracks :many
SELECT t.id, t.disc, t.no, t.title, t.artist, t.genre, t.source_path,
       t.blob_hash, b.size AS blob_size, b.format AS blob_format,
       (b.duration_ms IS NOT NULL)::boolean AS blob_duration_known,
       t.lyrics_hash, lb.size AS lyrics_size
FROM tracks t
JOIN blobs b ON b.hash = t.blob_hash
LEFT JOIN blobs lb ON lb.hash = t.lyrics_hash
WHERE t.album_id = $1
ORDER BY t.disc, t.no
`

type SnapshotTracksRow struct {
	ID                uuid.UUID
	Disc              int32
	No                int32
	Title             string
	Artist            *string
	Genre             *string
	SourcePath        string
	BlobHash          string
	BlobSize          int64
	BlobFormat        *string
	BlobDurationKnown bool
	LyricsHash        *string
	LyricsSize        *int64
}

// The render reads whether each audio blob's duration is known only to
// record it when it is not (NOTES.md N-301); the plan never uses it.
func (q *Queries) SnapshotTracks(ctx context.Context, albumID uuid.UUID) ([]SnapshotTracksRow, error) {
	rows, err := q.db.Query(ctx, snapshotTracks, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotTracksRow
	for rows.Next() {
		var i SnapshotTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.SourcePath,
			&i.BlobHash,
			&i.BlobSize,
			&i.BlobFormat,
			&i.BlobDurationKnown,
			&i.LyricsHash,
			&i.LyricsSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
