// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const rebuildActiveAlbums = `-- name: RebuildActiveAlbums :many
SELECT id FROM albums WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) RebuildActiveAlbums(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, rebuildActiveAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildClearClaims = `-- name: RebuildClearClaims :exec
DELETE FROM path_claims
`

func (q *Queries) RebuildClearClaims(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildClearClaims)
	return err
}

const rebuildClearJournal = `-- name: RebuildClearJournal :exec
DELETE FROM publication
`

// Offline rebuild (§11.3), always inside one InCatalogTx transaction.
// Clearing the journal before resetting the published state permits a
// repeat after a crash at any deletion or transaction boundary.
func (q *Queries) RebuildClearJournal(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildClearJournal)
	return err
}

const rebuildClearPublished = `-- name: RebuildClearPublished :exec
UPDATE albums SET published_path = NULL, published_revision = 0,
    published_renderer = NULL, published_build = NULL,
    published_receipt_hash = NULL
`

func (q *Queries) RebuildClearPublished(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildClearPublished)
	return err
}

const rebuildClearRenders = `-- name: RebuildClearRenders :exec
DELETE FROM jobs WHERE kind = 'render'
`

func (q *Queries) RebuildClearRenders(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildClearRenders)
	return err
}

const restoreDatabaseObjects = `-- name: RestoreDatabaseObjects :one
SELECT count(*)::bigint FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = current_schema() AND c.relkind IN ('r', 'p', 'v', 'm', 'S')
`

// A restore is allowed only on a brand-new database (§11.4). Check before
// creating even goose's metadata table. Include sequences and views too.
func (q *Queries) RestoreDatabaseObjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, restoreDatabaseObjects)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const restoreFailSourceJobs = `-- name: RestoreFailSourceJobs :execrows
UPDATE jobs SET state='failed', claimed=NULL, error_code='source_needs_verification',
    error_message='Verify or remount the import source and retry this job after restore.',
    updated_at=now()
WHERE kind IN ('scan','import') AND state IN ('pending','running')
`

func (q *Queries) RestoreFailSourceJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, restoreFailSourceJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const schemaVersionTableExists = `-- name: SchemaVersionTableExists :one
SELECT (to_regclass('goose_db_version') IS NOT NULL)::boolean AS present
`

// Offline commands read the schema version without creating goose's table
// (§11.3: doctor is read-only; goose's GetDBVersion would create it).
func (q *Queries) SchemaVersionTableExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, schemaVersionTableExists)
	var present bool
	err := row.Scan(&present)
	return present, err
}
