// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrate.sql

package store

import (
	"context"
)

const lockMigrations = `-- name: LockMigrations :exec
SELECT pg_advisory_lock(7884797347093438836)
`

// Serializes store.Migrate callers. Session-level, on a dedicated connection:
// closing it releases the lock even when the unlock never runs. The key is the
// ASCII "mlmigrat", distinct from the catalog lock of §5.3.
func (q *Queries) LockMigrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockMigrations)
	return err
}
