// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Album struct {
	ID                   uuid.UUID
	ArtistID             uuid.UUID
	Title                string
	FolderKey            string
	Year                 *int32
	Genre                *string
	Compilation          bool
	CoverHash            *string
	Revision             int64
	DeletedAt            *time.Time
	ImportFingerprint    *string
	PublishedPath        *string
	PublishedRevision    int64
	PublishedRenderer    *string
	PublishedBuild       *uuid.UUID
	PublishedReceiptHash *string
}

type Artist struct {
	ID        uuid.UUID
	Name      string
	FolderKey string
	Revision  int64
}

type Attachment struct {
	ID       uuid.UUID
	AlbumID  uuid.UUID
	RelPath  string
	PathKey  string
	BlobHash string
}

type Blob struct {
	Hash       string
	Size       int64
	Format     *string
	CreatedAt  time.Time
	DurationMs *int64
}

type ImportBatch struct {
	ID        uuid.UUID
	RootRel   string
	CreatedAt time.Time
}

type Job struct {
	ID            uuid.UUID
	Kind          string
	AlbumID       *uuid.UUID
	BatchID       *uuid.UUID
	SourceRel     *string
	Overrides     []byte
	Requested     int64
	Claimed       *int64
	State         string
	ResultAlbumID *uuid.UUID
	ErrorCode     *string
	ErrorMessage  *string
	Warnings      []byte
	QueuedAt      time.Time
	UpdatedAt     time.Time
	DismissedAt   *time.Time
}

type PathClaim struct {
	PathKey string
	Path    string
	AlbumID uuid.UUID
}

type Publication struct {
	ID          int16
	AlbumID     uuid.UUID
	Ticket      int64
	Revision    int64
	Renderer    string
	BuildID     uuid.UUID
	ReceiptHash *string
	OldPath     *string
	OldBuild    *uuid.UUID
	NewPath     *string
}

type Setting struct {
	ID      int16
	StoreID uuid.UUID
}

type Track struct {
	ID         uuid.UUID
	AlbumID    uuid.UUID
	Disc       int32
	No         int32
	Title      string
	Artist     *string
	Genre      *string
	BlobHash   string
	SourcePath string
	LyricsHash *string
}
