// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publish.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteJournal = `-- name: DeleteJournal :execrows
DELETE FROM publication WHERE id = 1 AND album_id = $1 AND build_id = $2
`

type DeleteJournalParams struct {
	AlbumID uuid.UUID
	BuildID uuid.UUID
}

// FINALIZE (§9.3 C).
func (q *Queries) DeleteJournal(ctx context.Context, arg DeleteJournalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJournal, arg.AlbumID, arg.BuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJournal = `-- name: GetJournal :one

SELECT id, album_id, ticket, revision, renderer, build_id, receipt_hash, old_path, old_build, new_path FROM publication WHERE id = 1
`

// The publication journal (DESIGN.md §9.3, §9.4): zero or one row, written
// by PREPARE and deleted by FINALIZE, each in a short transaction under the
// catalog lock (store.InCatalogTx). The paths are relative to library/ and
// exact (§5.3): never keys.
func (q *Queries) GetJournal(ctx context.Context) (Publication, error) {
	row := q.db.QueryRow(ctx, getJournal)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Ticket,
		&i.Revision,
		&i.Renderer,
		&i.BuildID,
		&i.ReceiptHash,
		&i.OldPath,
		&i.OldBuild,
		&i.NewPath,
	)
	return i, err
}

const getJournalForUpdate = `-- name: GetJournalForUpdate :one
SELECT id, album_id, ticket, revision, renderer, build_id, receipt_hash, old_path, old_build, new_path FROM publication WHERE id = 1 FOR UPDATE
`

func (q *Queries) GetJournalForUpdate(ctx context.Context) (Publication, error) {
	row := q.db.QueryRow(ctx, getJournalForUpdate)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Ticket,
		&i.Revision,
		&i.Renderer,
		&i.BuildID,
		&i.ReceiptHash,
		&i.OldPath,
		&i.OldBuild,
		&i.NewPath,
	)
	return i, err
}

const getRenderJobForUpdate = `-- name: GetRenderJobForUpdate :one
SELECT id, kind, album_id, batch_id, source_rel, overrides, requested, claimed, state, result_album_id, error_code, error_message, warnings, queued_at, updated_at FROM jobs WHERE kind = 'render' AND album_id = $1 FOR UPDATE
`

// The album's single render row (§4.2), locked: FINALIZE completes the
// attempt the journal names by its ticket (§6.4, N-107).
func (q *Queries) GetRenderJobForUpdate(ctx context.Context, albumID *uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getRenderJobForUpdate, albumID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AlbumID,
		&i.BatchID,
		&i.SourceRel,
		&i.Overrides,
		&i.Requested,
		&i.Claimed,
		&i.State,
		&i.ResultAlbumID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Warnings,
		&i.QueuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJournal = `-- name: InsertJournal :exec
INSERT INTO publication (id, album_id, ticket, revision, renderer, build_id, receipt_hash, old_path, old_build, new_path)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertJournalParams struct {
	AlbumID     uuid.UUID
	Ticket      int64
	Revision    int64
	Renderer    string
	BuildID     uuid.UUID
	ReceiptHash *string
	OldPath     *string
	OldBuild    *uuid.UUID
	NewPath     *string
}

// PREPARE (§9.3 A). The primary key (id = 1) refuses a second journal.
func (q *Queries) InsertJournal(ctx context.Context, arg InsertJournalParams) error {
	_, err := q.db.Exec(ctx, insertJournal,
		arg.AlbumID,
		arg.Ticket,
		arg.Revision,
		arg.Renderer,
		arg.BuildID,
		arg.ReceiptHash,
		arg.OldPath,
		arg.OldBuild,
		arg.NewPath,
	)
	return err
}

const setAlbumPublished = `-- name: SetAlbumPublished :execrows
UPDATE albums SET
    published_path = $1,
    published_revision = $2,
    published_renderer = $3,
    published_build = $4,
    published_receipt_hash = $5
WHERE id = $6
`

type SetAlbumPublishedParams struct {
	Path        *string
	Revision    int64
	Renderer    *string
	Build       *uuid.UUID
	ReceiptHash *string
	ID          uuid.UUID
}

// FINALIZE (§9.3 C): the published state is the journal's, never the
// album's current revision (§6.3). A removal has no path, build or receipt.
func (q *Queries) SetAlbumPublished(ctx context.Context, arg SetAlbumPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAlbumPublished,
		arg.Path,
		arg.Revision,
		arg.Renderer,
		arg.Build,
		arg.ReceiptHash,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
