// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const catalogIsEmpty = `-- name: CatalogIsEmpty :one
SELECT COALESCE(NOT EXISTS (SELECT 1 FROM blobs)
            AND NOT EXISTS (SELECT 1 FROM artists)
            AND NOT EXISTS (SELECT 1 FROM albums)
            AND NOT EXISTS (SELECT 1 FROM import_batches)
            AND NOT EXISTS (SELECT 1 FROM jobs), false)::boolean AS empty
`

// Whether the database is still in its first-initialization state (§2.2,
// §11.1): a missing volume marker may be completed only when nothing was ever
// imported, uploaded, created or queued. Every other catalog table references
// one of these (tracks, attachments and path claims need an album or an
// artist; the publication journal needs an album).
// COALESCE only tells sqlc that the result is never NULL.
func (q *Queries) CatalogIsEmpty(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, catalogIsEmpty)
	var empty bool
	err := row.Scan(&empty)
	return empty, err
}

const getStoreID = `-- name: GetStoreID :one
SELECT store_id FROM settings WHERE id = 1
`

func (q *Queries) GetStoreID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getStoreID)
	var store_id uuid.UUID
	err := row.Scan(&store_id)
	return store_id, err
}

const insertStoreID = `-- name: InsertStoreID :execrows
INSERT INTO settings (id, store_id) VALUES (1, $1)
ON CONFLICT (id) DO NOTHING
`

// First initialization (§11.1): a repeated or concurrent init keeps the first
// value; the caller reads it back with GetStoreID.
func (q *Queries) InsertStoreID(ctx context.Context, storeID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, insertStoreID, storeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
