// Package store owns the PostgreSQL side of musiclib (DESIGN.md §2.3): the
// connection pool, the embedded goose migrations and the sqlc queries of
// sql/. It never touches media and knows no absolute paths.
package store

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"musiclib/migrations"
)

// Error codes of the store. They are stable: boot reports them to the
// operator, who must act differently on each.
const (
	// CodeSchemaTooNew is a database already migrated by a newer binary.
	// Migrations are forward only (§11.4): older code must not run on it.
	CodeSchemaTooNew = "store_schema_too_new"
	// CodeMigrate is any other failure while applying migrations.
	CodeMigrate = "store_migrate"
)

// Error is the package's typed error; Err keeps the pgx or goose cause.
type Error struct {
	Code string
	Msg  string
	Err  error
}

func (e *Error) Error() string {
	msg := e.Code + ": " + e.Msg
	if e.Err != nil {
		msg += ": " + e.Err.Error()
	}
	return msg
}

func (e *Error) Unwrap() error { return e.Err }

// Code returns the code of the first *Error in err's tree, otherwise "".
func Code(err error) string {
	var e *Error
	if errors.As(err, &e) {
		return e.Code
	}
	return ""
}

// NewPool returns the application's pool (§11.1): at most workers+8
// connections, where workers is the already validated WORKERS (§6.1).
func NewPool(ctx context.Context, databaseURL string, workers int) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	cfg.MaxConns = int32(workers + 8)
	return pgxpool.NewWithConfig(ctx, cfg)
}

// Migrate applies the embedded migrations forward (§11.1: before any worker
// starts). It is safe at every boot and between concurrent callers, which
// wait on a blocking advisory lock (goose's own locker polls every 5 s).
// The lock lives on a dedicated connection outside the pool, so closing it
// releases the lock on every path, a crash included.
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	conn, err := pgx.ConnectConfig(ctx, pool.Config().ConnConfig.Copy())
	if err != nil {
		return &Error{Code: CodeMigrate, Msg: "connecting for the migration lock", Err: err}
	}
	defer conn.Close(context.WithoutCancel(ctx))
	if err := New(conn).LockMigrations(ctx); err != nil {
		return &Error{Code: CodeMigrate, Msg: "acquiring the migration lock", Err: err}
	}

	db := stdlib.OpenDBFromPool(pool)
	defer db.Close()
	p, err := goose.NewProvider(goose.DialectPostgres, db, migrations.FS, goose.WithDisableGlobalRegistry(true))
	if err != nil {
		return &Error{Code: CodeMigrate, Msg: "loading migrations", Err: err}
	}
	current, err := p.GetDBVersion(ctx)
	if err != nil {
		return &Error{Code: CodeMigrate, Msg: "reading the schema version", Err: err}
	}
	sources := p.ListSources()
	if latest := sources[len(sources)-1].Version; current > latest {
		return &Error{Code: CodeSchemaTooNew, Msg: fmt.Sprintf("database schema version %d, this binary knows up to %d", current, latest)}
	}
	if _, err := p.Up(ctx); err != nil {
		return &Error{Code: CodeMigrate, Msg: "applying migrations", Err: err}
	}
	return nil
}

// NewID returns a new row identifier (§2.1: UUIDv7 generated by the
// application). Time-ordered, so new rows land at the right edge of the
// primary-key index; google/uuid also makes it strictly increasing within
// the process. NewV7 fails only if crypto/rand does, which since Go 1.24
// crashes the program instead of returning an error.
func NewID() uuid.UUID {
	return uuid.Must(uuid.NewV7())
}
